# coding: utf-8

"""
    Monad API

    This is the monad API

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from monad.models.models_condition_evaluatable import ModelsConditionEvaluatable

class TestModelsConditionEvaluatable(unittest.TestCase):
    """ModelsConditionEvaluatable unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelsConditionEvaluatable:
        """Test ModelsConditionEvaluatable
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelsConditionEvaluatable`
        """
        model = ModelsConditionEvaluatable()
        if include_optional:
            return ModelsConditionEvaluatable(
                conditions = [
                    monad.models.models/condition_evaluatable.models.ConditionEvaluatable(
                        conditions = [
                            monad.models.models/condition_evaluatable.models.ConditionEvaluatable(
                                config = {
                                    'key' : null
                                    }, 
                                operator = '', 
                                type_id = '', )
                            ], 
                        config = {
                            'key' : null
                            }, 
                        operator = '', 
                        type_id = '', )
                    ],
                config = {
                    'key' : null
                    },
                operator = '',
                type_id = ''
            )
        else:
            return ModelsConditionEvaluatable(
        )
        """

    def testModelsConditionEvaluatable(self):
        """Test ModelsConditionEvaluatable"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
