# coding: utf-8

"""
    Monad Swagger API

    This is the monad API

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from monad.models.routes_update_output_request import RoutesUpdateOutputRequest

class TestRoutesUpdateOutputRequest(unittest.TestCase):
    """RoutesUpdateOutputRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RoutesUpdateOutputRequest:
        """Test RoutesUpdateOutputRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RoutesUpdateOutputRequest`
        """
        model = RoutesUpdateOutputRequest()
        if include_optional:
            return RoutesUpdateOutputRequest(
                config = monad.models.models/input_config.models.InputConfig(
                    secrets = {
                        'key' : null
                        }, 
                    settings = {
                        'key' : null
                        }, ),
                description = '',
                name = '',
                output_type = ''
            )
        else:
            return RoutesUpdateOutputRequest(
                output_type = '',
        )
        """

    def testRoutesUpdateOutputRequest(self):
        """Test RoutesUpdateOutputRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
