# coding: utf-8

"""
    Monad API

    This is the monad API

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from monad.models.pipeline_node_status_progress_timestamps import PipelineNodeStatusProgressTimestamps

class TestPipelineNodeStatusProgressTimestamps(unittest.TestCase):
    """PipelineNodeStatusProgressTimestamps unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PipelineNodeStatusProgressTimestamps:
        """Test PipelineNodeStatusProgressTimestamps
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PipelineNodeStatusProgressTimestamps`
        """
        model = PipelineNodeStatusProgressTimestamps()
        if include_optional:
            return PipelineNodeStatusProgressTimestamps(
                timestamps = [
                    monad.models.pipeline_node_status/progress_timestamp.pipeline_node_status.ProgressTimestamp(
                        label = '', 
                        partition_key = '', 
                        timestamp = '', )
                    ]
            )
        else:
            return PipelineNodeStatusProgressTimestamps(
        )
        """

    def testPipelineNodeStatusProgressTimestamps(self):
        """Test PipelineNodeStatusProgressTimestamps"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
