# coding: utf-8

"""
    Monad API

    This is the monad API

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from monad.models.aws_iam_aliases_settings_config import AwsIamAliasesSettingsConfig

class TestAwsIamAliasesSettingsConfig(unittest.TestCase):
    """AwsIamAliasesSettingsConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AwsIamAliasesSettingsConfig:
        """Test AwsIamAliasesSettingsConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AwsIamAliasesSettingsConfig`
        """
        model = AwsIamAliasesSettingsConfig()
        if include_optional:
            return AwsIamAliasesSettingsConfig(
                accounts = [
                    monad.models.aws_iam_aliases/account.aws_iam_aliases.Account(
                        account_id = '', 
                        role_name = '', )
                    ],
                cron = '',
                use_synthetic_data = True
            )
        else:
            return AwsIamAliasesSettingsConfig(
        )
        """

    def testAwsIamAliasesSettingsConfig(self):
        """Test AwsIamAliasesSettingsConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
