/*
 * Monad API
 * This is the monad API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ModelsSecret;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Clumio Alerts secrets
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-06T20:23:46.300522105Z[Etc/UTC]", comments = "Generator version: 7.14.0")
public class ClumioConsolidatedAlertsSecretsConfig {
  public static final String SERIALIZED_NAME_ACCESS_TOKEN = "access_token";
  @SerializedName(SERIALIZED_NAME_ACCESS_TOKEN)
  @javax.annotation.Nullable
  private ModelsSecret accessToken;

  public ClumioConsolidatedAlertsSecretsConfig() {
  }

  public ClumioConsolidatedAlertsSecretsConfig accessToken(@javax.annotation.Nullable ModelsSecret accessToken) {
    this.accessToken = accessToken;
    return this;
  }

  /**
   * Get accessToken
   * @return accessToken
   */
  @javax.annotation.Nullable
  public ModelsSecret getAccessToken() {
    return accessToken;
  }

  public void setAccessToken(@javax.annotation.Nullable ModelsSecret accessToken) {
    this.accessToken = accessToken;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClumioConsolidatedAlertsSecretsConfig clumioConsolidatedAlertsSecretsConfig = (ClumioConsolidatedAlertsSecretsConfig) o;
    return Objects.equals(this.accessToken, clumioConsolidatedAlertsSecretsConfig.accessToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClumioConsolidatedAlertsSecretsConfig {\n");
    sb.append("    accessToken: ").append(toIndentedString(accessToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("access_token"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ClumioConsolidatedAlertsSecretsConfig
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ClumioConsolidatedAlertsSecretsConfig.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ClumioConsolidatedAlertsSecretsConfig is not found in the empty JSON string", ClumioConsolidatedAlertsSecretsConfig.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ClumioConsolidatedAlertsSecretsConfig.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ClumioConsolidatedAlertsSecretsConfig` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `access_token`
      if (jsonObj.get("access_token") != null && !jsonObj.get("access_token").isJsonNull()) {
        ModelsSecret.validateJsonElement(jsonObj.get("access_token"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ClumioConsolidatedAlertsSecretsConfig.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ClumioConsolidatedAlertsSecretsConfig' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ClumioConsolidatedAlertsSecretsConfig> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ClumioConsolidatedAlertsSecretsConfig.class));

       return (TypeAdapter<T>) new TypeAdapter<ClumioConsolidatedAlertsSecretsConfig>() {
           @Override
           public void write(JsonWriter out, ClumioConsolidatedAlertsSecretsConfig value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ClumioConsolidatedAlertsSecretsConfig read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ClumioConsolidatedAlertsSecretsConfig given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ClumioConsolidatedAlertsSecretsConfig
   * @throws IOException if the JSON string is invalid with respect to ClumioConsolidatedAlertsSecretsConfig
   */
  public static ClumioConsolidatedAlertsSecretsConfig fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ClumioConsolidatedAlertsSecretsConfig.class);
  }

  /**
   * Convert an instance of ClumioConsolidatedAlertsSecretsConfig to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

