/*
 * Monad API
 * This is the monad API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.client.model.ModelsUserRoleWithPermissions;
import org.openapitools.client.model.RoutesUserAuthProvider;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * RoutesUserWithRoles
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-19T20:06:55.115515435Z[Etc/UTC]", comments = "Generator version: 7.20.0")
public class RoutesUserWithRoles {
  public static final String SERIALIZED_NAME_AUTH_PROVIDER = "auth_provider";
  @SerializedName(SERIALIZED_NAME_AUTH_PROVIDER)
  @javax.annotation.Nullable
  private RoutesUserAuthProvider authProvider;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private String createdAt;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  @javax.annotation.Nullable
  private String email;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_ORGANIZATION_ROLES = "organization_roles";
  @SerializedName(SERIALIZED_NAME_ORGANIZATION_ROLES)
  @javax.annotation.Nullable
  private Map<String, ModelsUserRoleWithPermissions> organizationRoles = new HashMap<>();

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nullable
  private String updatedAt;

  public static final String SERIALIZED_NAME_USERNAME = "username";
  @SerializedName(SERIALIZED_NAME_USERNAME)
  @javax.annotation.Nullable
  private String username;

  public RoutesUserWithRoles() {
  }

  public RoutesUserWithRoles authProvider(@javax.annotation.Nullable RoutesUserAuthProvider authProvider) {
    this.authProvider = authProvider;
    return this;
  }

  /**
   * Get authProvider
   * @return authProvider
   */
  @javax.annotation.Nullable
  public RoutesUserAuthProvider getAuthProvider() {
    return authProvider;
  }

  public void setAuthProvider(@javax.annotation.Nullable RoutesUserAuthProvider authProvider) {
    this.authProvider = authProvider;
  }


  public RoutesUserWithRoles createdAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
  }


  public RoutesUserWithRoles email(@javax.annotation.Nullable String email) {
    this.email = email;
    return this;
  }

  /**
   * Get email
   * @return email
   */
  @javax.annotation.Nullable
  public String getEmail() {
    return email;
  }

  public void setEmail(@javax.annotation.Nullable String email) {
    this.email = email;
  }


  public RoutesUserWithRoles id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public RoutesUserWithRoles organizationRoles(@javax.annotation.Nullable Map<String, ModelsUserRoleWithPermissions> organizationRoles) {
    this.organizationRoles = organizationRoles;
    return this;
  }

  public RoutesUserWithRoles putOrganizationRolesItem(String key, ModelsUserRoleWithPermissions organizationRolesItem) {
    if (this.organizationRoles == null) {
      this.organizationRoles = new HashMap<>();
    }
    this.organizationRoles.put(key, organizationRolesItem);
    return this;
  }

  /**
   * Get organizationRoles
   * @return organizationRoles
   */
  @javax.annotation.Nullable
  public Map<String, ModelsUserRoleWithPermissions> getOrganizationRoles() {
    return organizationRoles;
  }

  public void setOrganizationRoles(@javax.annotation.Nullable Map<String, ModelsUserRoleWithPermissions> organizationRoles) {
    this.organizationRoles = organizationRoles;
  }


  public RoutesUserWithRoles updatedAt(@javax.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nullable
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public RoutesUserWithRoles username(@javax.annotation.Nullable String username) {
    this.username = username;
    return this;
  }

  /**
   * Get username
   * @return username
   */
  @javax.annotation.Nullable
  public String getUsername() {
    return username;
  }

  public void setUsername(@javax.annotation.Nullable String username) {
    this.username = username;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RoutesUserWithRoles routesUserWithRoles = (RoutesUserWithRoles) o;
    return Objects.equals(this.authProvider, routesUserWithRoles.authProvider) &&
        Objects.equals(this.createdAt, routesUserWithRoles.createdAt) &&
        Objects.equals(this.email, routesUserWithRoles.email) &&
        Objects.equals(this.id, routesUserWithRoles.id) &&
        Objects.equals(this.organizationRoles, routesUserWithRoles.organizationRoles) &&
        Objects.equals(this.updatedAt, routesUserWithRoles.updatedAt) &&
        Objects.equals(this.username, routesUserWithRoles.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authProvider, createdAt, email, id, organizationRoles, updatedAt, username);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RoutesUserWithRoles {\n");
    sb.append("    authProvider: ").append(toIndentedString(authProvider)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    organizationRoles: ").append(toIndentedString(organizationRoles)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("auth_provider", "created_at", "email", "id", "organization_roles", "updated_at", "username"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RoutesUserWithRoles
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RoutesUserWithRoles.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in RoutesUserWithRoles is not found in the empty JSON string", RoutesUserWithRoles.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RoutesUserWithRoles.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `RoutesUserWithRoles` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `auth_provider`
      if (jsonObj.get("auth_provider") != null && !jsonObj.get("auth_provider").isJsonNull()) {
        RoutesUserAuthProvider.validateJsonElement(jsonObj.get("auth_provider"));
      }
      if ((jsonObj.get("created_at") != null && !jsonObj.get("created_at").isJsonNull()) && !jsonObj.get("created_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `created_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("created_at").toString()));
      }
      if ((jsonObj.get("email") != null && !jsonObj.get("email").isJsonNull()) && !jsonObj.get("email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email").toString()));
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("updated_at") != null && !jsonObj.get("updated_at").isJsonNull()) && !jsonObj.get("updated_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `updated_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("updated_at").toString()));
      }
      if ((jsonObj.get("username") != null && !jsonObj.get("username").isJsonNull()) && !jsonObj.get("username").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `username` to be a primitive type in the JSON string but got `%s`", jsonObj.get("username").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RoutesUserWithRoles.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RoutesUserWithRoles' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RoutesUserWithRoles> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RoutesUserWithRoles.class));

       return (TypeAdapter<T>) new TypeAdapter<RoutesUserWithRoles>() {
           @Override
           public void write(JsonWriter out, RoutesUserWithRoles value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RoutesUserWithRoles read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RoutesUserWithRoles given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RoutesUserWithRoles
   * @throws IOException if the JSON string is invalid with respect to RoutesUserWithRoles
   */
  public static RoutesUserWithRoles fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RoutesUserWithRoles.class);
  }

  /**
   * Convert an instance of RoutesUserWithRoles to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

