/*
 * Monad API
 * Programmatically manage your security data pipelines, configure data sources and destinations, and automate your security operations.  ## Base URL  ``` {{BASE_URL}}/api ```  ## Authentication  The Monad API supports two authentication methods:  ### API Key  Include your API key in the `x-api-key` header:  ```bash curl -H \"x-api-key: YOUR_API_KEY\" \\   {{BASE_URL}}/api/v2/organizations/{org_id}/pipelines ```  ### JWT Bearer Token  Include your JWT token in the `Authorization` header:  ```bash curl -H \"Authorization: Bearer YOUR_JWT_TOKEN\" \\   {{BASE_URL}}/api/v2/organizations/{org_id}/pipelines ```  ## Quick Start  List your pipelines:  ```bash curl -H \"x-api-key: YOUR_API_KEY\" \\   {{BASE_URL}}/api/v2/organizations/{org_id}/pipelines ```  Create a new pipeline:  ```bash curl -X POST \\   -H \"x-api-key: YOUR_API_KEY\" \\   -H \"Content-Type: application/json\" \\   -d '{\"name\": \"My Pipeline\", \"description\": \"Pipeline description\"}' \\   {{BASE_URL}}/api/v2/organizations/{org_id}/pipelines ```  ## Rate Limits  API requests are subject to rate limiting. If you exceed the rate limit, you'll receive a `429 Too Many Requests` response. Implement exponential backoff in your applications to handle rate limiting gracefully.  ## Errors  The API uses standard HTTP status codes:  | Status Code | Description                                      | | ----------- | ------------------------------------------------ | | `200`       | Success                                          | | `201`       | Created                                          | | `400`       | Bad Request - Invalid parameters                 | | `401`       | Unauthorized - Invalid or missing authentication | | `403`       | Forbidden - Insufficient permissions             | | `404`       | Not Found - Resource doesn't exist               | | `429`       | Too Many Requests - Rate limit exceeded          | | `500`       | Internal Server Error                            | 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@monad.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Details about the source AWS account and region for Security Lake
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class SecurityLakeSourceAccountDetails {
  public static final String SERIALIZED_NAME_SOURCE_ACCOUNT_ID = "source_account_id";
  @SerializedName(SERIALIZED_NAME_SOURCE_ACCOUNT_ID)
  @javax.annotation.Nullable
  private String sourceAccountId;

  public static final String SERIALIZED_NAME_SOURCE_REGION = "source_region";
  @SerializedName(SERIALIZED_NAME_SOURCE_REGION)
  @javax.annotation.Nullable
  private String sourceRegion;

  public SecurityLakeSourceAccountDetails() {
  }

  public SecurityLakeSourceAccountDetails sourceAccountId(@javax.annotation.Nullable String sourceAccountId) {
    this.sourceAccountId = sourceAccountId;
    return this;
  }

  /**
   * Source AWS Account ID
   * @return sourceAccountId
   */
  @javax.annotation.Nullable
  public String getSourceAccountId() {
    return sourceAccountId;
  }

  public void setSourceAccountId(@javax.annotation.Nullable String sourceAccountId) {
    this.sourceAccountId = sourceAccountId;
  }


  public SecurityLakeSourceAccountDetails sourceRegion(@javax.annotation.Nullable String sourceRegion) {
    this.sourceRegion = sourceRegion;
    return this;
  }

  /**
   * Source AWS Region
   * @return sourceRegion
   */
  @javax.annotation.Nullable
  public String getSourceRegion() {
    return sourceRegion;
  }

  public void setSourceRegion(@javax.annotation.Nullable String sourceRegion) {
    this.sourceRegion = sourceRegion;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SecurityLakeSourceAccountDetails securityLakeSourceAccountDetails = (SecurityLakeSourceAccountDetails) o;
    return Objects.equals(this.sourceAccountId, securityLakeSourceAccountDetails.sourceAccountId) &&
        Objects.equals(this.sourceRegion, securityLakeSourceAccountDetails.sourceRegion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sourceAccountId, sourceRegion);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SecurityLakeSourceAccountDetails {\n");
    sb.append("    sourceAccountId: ").append(toIndentedString(sourceAccountId)).append("\n");
    sb.append("    sourceRegion: ").append(toIndentedString(sourceRegion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("source_account_id", "source_region"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SecurityLakeSourceAccountDetails
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SecurityLakeSourceAccountDetails.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in SecurityLakeSourceAccountDetails is not found in the empty JSON string", SecurityLakeSourceAccountDetails.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SecurityLakeSourceAccountDetails.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `SecurityLakeSourceAccountDetails` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("source_account_id") != null && !jsonObj.get("source_account_id").isJsonNull()) && !jsonObj.get("source_account_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `source_account_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("source_account_id").toString()));
      }
      if ((jsonObj.get("source_region") != null && !jsonObj.get("source_region").isJsonNull()) && !jsonObj.get("source_region").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `source_region` to be a primitive type in the JSON string but got `%s`", jsonObj.get("source_region").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SecurityLakeSourceAccountDetails.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SecurityLakeSourceAccountDetails' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SecurityLakeSourceAccountDetails> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SecurityLakeSourceAccountDetails.class));

       return (TypeAdapter<T>) new TypeAdapter<SecurityLakeSourceAccountDetails>() {
           @Override
           public void write(JsonWriter out, SecurityLakeSourceAccountDetails value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SecurityLakeSourceAccountDetails read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SecurityLakeSourceAccountDetails given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SecurityLakeSourceAccountDetails
   * @throws IOException if the JSON string is invalid with respect to SecurityLakeSourceAccountDetails
   */
  public static SecurityLakeSourceAccountDetails fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SecurityLakeSourceAccountDetails.class);
  }

  /**
   * Convert an instance of SecurityLakeSourceAccountDetails to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

