/*
 * Monad API
 * This is the monad API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Zendesk Audit Logs settings
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-29T18:07:38.362554792Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class ZendeskAuditLogsSettingsConfig {
  public static final String SERIALIZED_NAME_AUTH_TYPE = "auth_type";
  @SerializedName(SERIALIZED_NAME_AUTH_TYPE)
  @javax.annotation.Nullable
  private String authType;

  public static final String SERIALIZED_NAME_EMAIL_ADDRESS = "email_address";
  @SerializedName(SERIALIZED_NAME_EMAIL_ADDRESS)
  @javax.annotation.Nullable
  private String emailAddress;

  public static final String SERIALIZED_NAME_SUB_DOMAIN = "sub_domain";
  @SerializedName(SERIALIZED_NAME_SUB_DOMAIN)
  @javax.annotation.Nullable
  private String subDomain;

  public static final String SERIALIZED_NAME_USE_SYNTHETIC_DATA = "use_synthetic_data";
  @SerializedName(SERIALIZED_NAME_USE_SYNTHETIC_DATA)
  @javax.annotation.Nullable
  private Boolean useSyntheticData;

  public ZendeskAuditLogsSettingsConfig() {
  }

  public ZendeskAuditLogsSettingsConfig authType(@javax.annotation.Nullable String authType) {
    this.authType = authType;
    return this;
  }

  /**
   * AuthType is the type of authentication used for the input
   * @return authType
   */
  @javax.annotation.Nullable
  public String getAuthType() {
    return authType;
  }

  public void setAuthType(@javax.annotation.Nullable String authType) {
    this.authType = authType;
  }


  public ZendeskAuditLogsSettingsConfig emailAddress(@javax.annotation.Nullable String emailAddress) {
    this.emailAddress = emailAddress;
    return this;
  }

  /**
   * This is the email address registered with your Zendesk account
   * @return emailAddress
   */
  @javax.annotation.Nullable
  public String getEmailAddress() {
    return emailAddress;
  }

  public void setEmailAddress(@javax.annotation.Nullable String emailAddress) {
    this.emailAddress = emailAddress;
  }


  public ZendeskAuditLogsSettingsConfig subDomain(@javax.annotation.Nullable String subDomain) {
    this.subDomain = subDomain;
    return this;
  }

  /**
   * This is the subdomain found in your Zendesk account URL For example, if the URL is https://demo.zendesk.com then the subdomain will be demo
   * @return subDomain
   */
  @javax.annotation.Nullable
  public String getSubDomain() {
    return subDomain;
  }

  public void setSubDomain(@javax.annotation.Nullable String subDomain) {
    this.subDomain = subDomain;
  }


  public ZendeskAuditLogsSettingsConfig useSyntheticData(@javax.annotation.Nullable Boolean useSyntheticData) {
    this.useSyntheticData = useSyntheticData;
    return this;
  }

  /**
   * Generate synthetic demo data instead of connecting to the real data source.
   * @return useSyntheticData
   */
  @javax.annotation.Nullable
  public Boolean getUseSyntheticData() {
    return useSyntheticData;
  }

  public void setUseSyntheticData(@javax.annotation.Nullable Boolean useSyntheticData) {
    this.useSyntheticData = useSyntheticData;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ZendeskAuditLogsSettingsConfig zendeskAuditLogsSettingsConfig = (ZendeskAuditLogsSettingsConfig) o;
    return Objects.equals(this.authType, zendeskAuditLogsSettingsConfig.authType) &&
        Objects.equals(this.emailAddress, zendeskAuditLogsSettingsConfig.emailAddress) &&
        Objects.equals(this.subDomain, zendeskAuditLogsSettingsConfig.subDomain) &&
        Objects.equals(this.useSyntheticData, zendeskAuditLogsSettingsConfig.useSyntheticData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authType, emailAddress, subDomain, useSyntheticData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ZendeskAuditLogsSettingsConfig {\n");
    sb.append("    authType: ").append(toIndentedString(authType)).append("\n");
    sb.append("    emailAddress: ").append(toIndentedString(emailAddress)).append("\n");
    sb.append("    subDomain: ").append(toIndentedString(subDomain)).append("\n");
    sb.append("    useSyntheticData: ").append(toIndentedString(useSyntheticData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("auth_type", "email_address", "sub_domain", "use_synthetic_data"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ZendeskAuditLogsSettingsConfig
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ZendeskAuditLogsSettingsConfig.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ZendeskAuditLogsSettingsConfig is not found in the empty JSON string", ZendeskAuditLogsSettingsConfig.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ZendeskAuditLogsSettingsConfig.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ZendeskAuditLogsSettingsConfig` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("auth_type") != null && !jsonObj.get("auth_type").isJsonNull()) && !jsonObj.get("auth_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `auth_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("auth_type").toString()));
      }
      if ((jsonObj.get("email_address") != null && !jsonObj.get("email_address").isJsonNull()) && !jsonObj.get("email_address").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `email_address` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email_address").toString()));
      }
      if ((jsonObj.get("sub_domain") != null && !jsonObj.get("sub_domain").isJsonNull()) && !jsonObj.get("sub_domain").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `sub_domain` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sub_domain").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ZendeskAuditLogsSettingsConfig.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ZendeskAuditLogsSettingsConfig' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ZendeskAuditLogsSettingsConfig> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ZendeskAuditLogsSettingsConfig.class));

       return (TypeAdapter<T>) new TypeAdapter<ZendeskAuditLogsSettingsConfig>() {
           @Override
           public void write(JsonWriter out, ZendeskAuditLogsSettingsConfig value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ZendeskAuditLogsSettingsConfig read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ZendeskAuditLogsSettingsConfig given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ZendeskAuditLogsSettingsConfig
   * @throws IOException if the JSON string is invalid with respect to ZendeskAuditLogsSettingsConfig
   */
  public static ZendeskAuditLogsSettingsConfig fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ZendeskAuditLogsSettingsConfig.class);
  }

  /**
   * Convert an instance of ZendeskAuditLogsSettingsConfig to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

