/**
 * Monad API
 * This is the monad API
 *
 * OpenAPI spec version: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ModelsPagination } from '../models/ModelsPagination';
import { ModelsPermission } from '../models/ModelsPermission';
import { HttpFile } from '../http/http';

export class ModelsPermissionList {
    'pagination'?: ModelsPagination;
    'permissions'?: Array<ModelsPermission>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pagination",
            "baseName": "pagination",
            "type": "ModelsPagination",
            "format": ""
        },
        {
            "name": "permissions",
            "baseName": "permissions",
            "type": "Array<ModelsPermission>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModelsPermissionList.attributeTypeMap;
    }

    public constructor() {
    }
}
