/**
 * Monad API
 * Programmatically manage your security data pipelines, configure data sources and destinations, and automate your security operations.  ## Base URL  ``` {{BASE_URL}}/api ```  ## Authentication  The Monad API supports two authentication methods:  ### API Key  Include your API key in the `x-api-key` header:  ```bash curl -H \"x-api-key: YOUR_API_KEY\" \\   {{BASE_URL}}/api/v2/organizations/{org_id}/pipelines ```  ### JWT Bearer Token  Include your JWT token in the `Authorization` header:  ```bash curl -H \"Authorization: Bearer YOUR_JWT_TOKEN\" \\   {{BASE_URL}}/api/v2/organizations/{org_id}/pipelines ```  ## Quick Start  List your pipelines:  ```bash curl -H \"x-api-key: YOUR_API_KEY\" \\   {{BASE_URL}}/api/v2/organizations/{org_id}/pipelines ```  Create a new pipeline:  ```bash curl -X POST \\   -H \"x-api-key: YOUR_API_KEY\" \\   -H \"Content-Type: application/json\" \\   -d \'{\"name\": \"My Pipeline\", \"description\": \"Pipeline description\"}\' \\   {{BASE_URL}}/api/v2/organizations/{org_id}/pipelines ```  ## Rate Limits  API requests are subject to rate limiting. If you exceed the rate limit, you\'ll receive a `429 Too Many Requests` response. Implement exponential backoff in your applications to handle rate limiting gracefully.  ## Errors  The API uses standard HTTP status codes:  | Status Code | Description                                      | | ----------- | ------------------------------------------------ | | `200`       | Success                                          | | `201`       | Created                                          | | `400`       | Bad Request - Invalid parameters                 | | `401`       | Unauthorized - Invalid or missing authentication | | `403`       | Forbidden - Insufficient permissions             | | `404`       | Not Found - Resource doesn\'t exist               | | `429`       | Too Many Requests - Rate limit exceeded          | | `500`       | Internal Server Error                            | 
 *
 * OpenAPI spec version: 1.0
 * Contact: support@monad.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ModelsManagedBy } from '../models/ModelsManagedBy';
import { ModelsPipelineEdge } from '../models/ModelsPipelineEdge';
import { ModelsPipelineNode } from '../models/ModelsPipelineNode';
import { ModelsPipelineRetentionPolicy } from '../models/ModelsPipelineRetentionPolicy';
import { ModelsPipelineStatus } from '../models/ModelsPipelineStatus';
import { HttpFile } from '../http/http';

export class ModelsPipelineConfigV2 {
    'billingAccountId'?: string;
    'componentTier'?: number;
    'createdAt'?: string;
    'cronSchedule'?: string;
    'description'?: string;
    'edges'?: Array<ModelsPipelineEdge>;
    'enabled'?: boolean;
    'id'?: string;
    'isSynthetic'?: boolean;
    'managedBy'?: ModelsManagedBy;
    'name'?: string;
    'nextCronRunAt'?: string;
    'nodes'?: Array<ModelsPipelineNode>;
    'organizationId'?: string;
    'organizationName'?: string;
    'retentionPolicy'?: ModelsPipelineRetentionPolicy;
    'status'?: ModelsPipelineStatus;
    'updatedAt'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "billingAccountId",
            "baseName": "billingAccountId",
            "type": "string",
            "format": ""
        },
        {
            "name": "componentTier",
            "baseName": "component_tier",
            "type": "number",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "cronSchedule",
            "baseName": "cron_schedule",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "edges",
            "baseName": "edges",
            "type": "Array<ModelsPipelineEdge>",
            "format": ""
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "isSynthetic",
            "baseName": "is_synthetic",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "managedBy",
            "baseName": "managed_by",
            "type": "ModelsManagedBy",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "nextCronRunAt",
            "baseName": "next_cron_run_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "nodes",
            "baseName": "nodes",
            "type": "Array<ModelsPipelineNode>",
            "format": ""
        },
        {
            "name": "organizationId",
            "baseName": "organizationId",
            "type": "string",
            "format": ""
        },
        {
            "name": "organizationName",
            "baseName": "organizationName",
            "type": "string",
            "format": ""
        },
        {
            "name": "retentionPolicy",
            "baseName": "retention_policy",
            "type": "ModelsPipelineRetentionPolicy",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ModelsPipelineStatus",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModelsPipelineConfigV2.attributeTypeMap;
    }

    public constructor() {
    }
}


