/**
 * Monad API
 * This is the monad API
 *
 * OpenAPI spec version: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BigquerySettingsConfig } from '../models/BigquerySettingsConfig';
import { CriblHttpSettingsConfig } from '../models/CriblHttpSettingsConfig';
import { ElasticsearchSettingsConfig } from '../models/ElasticsearchSettingsConfig';
import { HttpSettingsConfig } from '../models/HttpSettingsConfig';
import { NextGenSiemSettingsConfig } from '../models/NextGenSiemSettingsConfig';
import { OpensearchSettingsConfig } from '../models/OpensearchSettingsConfig';
import { PostgresqlSettingsConfig } from '../models/PostgresqlSettingsConfig';
import { S3SettingsConfig } from '../models/S3SettingsConfig';
import { SentinelSettingsConfig } from '../models/SentinelSettingsConfig';
import { SnowflakeOutputSettingsConfig } from '../models/SnowflakeOutputSettingsConfig';
import { SplunkSettingsConfig } from '../models/SplunkSettingsConfig';
import { SumologicSettingsConfig } from '../models/SumologicSettingsConfig';
import { HttpFile } from '../http/http';

/**
 * @type RoutesV2OutputConfigSettings
 * Type
 * @export
 */
export type RoutesV2OutputConfigSettings = BigquerySettingsConfig | CriblHttpSettingsConfig | ElasticsearchSettingsConfig | HttpSettingsConfig | NextGenSiemSettingsConfig | OpensearchSettingsConfig | PostgresqlSettingsConfig | S3SettingsConfig | SentinelSettingsConfig | SnowflakeOutputSettingsConfig | SplunkSettingsConfig | SumologicSettingsConfig | { [key: string]: any; };

/**
* @type RoutesV2OutputConfigSettingsClass
* @export
*/
export class RoutesV2OutputConfigSettingsClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}












