/**
 * Monad API
 * This is the monad API
 *
 * OpenAPI spec version: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Tines Events Logs settings
*/
export class TinesEventsLogsSettingsConfig {
    /**
    * Date to start fetching data from. If not specified, a full sync of is fetched on the first sync. All syncs thereafter will be incremental.
    */
    'backfillStartTime'?: string;
    /**
    * Filter by the given story.
    */
    'storyId'?: string;
    /**
    * Filter by the given team.
    */
    'teamId'?: string;
    /**
    * Unique URL for your Tines instance
    */
    'tenantUrl'?: string;
    /**
    * Generate synthetic demo data instead of connecting to the real data source.
    */
    'useSyntheticData'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "backfillStartTime",
            "baseName": "backfill_start_time",
            "type": "string",
            "format": ""
        },
        {
            "name": "storyId",
            "baseName": "story_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "teamId",
            "baseName": "team_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "tenantUrl",
            "baseName": "tenant_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "useSyntheticData",
            "baseName": "use_synthetic_data",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TinesEventsLogsSettingsConfig.attributeTypeMap;
    }

    public constructor() {
    }
}
