/**
 * Monad Swagger API
 * This is the monad API
 *
 * OpenAPI spec version: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Google Workspace Users secrets
*/
export class UsersSecretsConfig {
    /**
    * JSON credentials to authenticate with Google Cloud.
    */
    'credentialsJson'?: string;
    /**
    * Google Workspace Customer ID. If you use your google workspace customer ID you will pull data on all users in all domains of your Google Workspace account. This should be set if Domain is not set.
    */
    'customerId'?: string;
    /**
    * Domain name your users belong to. If you use a google workspace domain you will only pull user data for users that belong to that domain. This should be set if CustomerID is not set
    */
    'domain'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "credentialsJson",
            "baseName": "credentials_json",
            "type": "string",
            "format": ""
        },
        {
            "name": "customerId",
            "baseName": "customer_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "domain",
            "baseName": "domain",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UsersSecretsConfig.attributeTypeMap;
    }

    public constructor() {
    }
}
