/*
Monad API

This is the monad API

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package monad

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WizAuditLogsSecretsConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WizAuditLogsSecretsConfig{}

// WizAuditLogsSecretsConfig Wiz Audit Logs secrets
type WizAuditLogsSecretsConfig struct {
	ClientId ModelsSecret `json:"client_id"`
	ClientSecret ModelsSecret `json:"client_secret"`
}

type _WizAuditLogsSecretsConfig WizAuditLogsSecretsConfig

// NewWizAuditLogsSecretsConfig instantiates a new WizAuditLogsSecretsConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWizAuditLogsSecretsConfig(clientId ModelsSecret, clientSecret ModelsSecret) *WizAuditLogsSecretsConfig {
	this := WizAuditLogsSecretsConfig{}
	this.ClientId = clientId
	this.ClientSecret = clientSecret
	return &this
}

// NewWizAuditLogsSecretsConfigWithDefaults instantiates a new WizAuditLogsSecretsConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWizAuditLogsSecretsConfigWithDefaults() *WizAuditLogsSecretsConfig {
	this := WizAuditLogsSecretsConfig{}
	return &this
}

// GetClientId returns the ClientId field value
func (o *WizAuditLogsSecretsConfig) GetClientId() ModelsSecret {
	if o == nil {
		var ret ModelsSecret
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *WizAuditLogsSecretsConfig) GetClientIdOk() (*ModelsSecret, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *WizAuditLogsSecretsConfig) SetClientId(v ModelsSecret) {
	o.ClientId = v
}

// GetClientSecret returns the ClientSecret field value
func (o *WizAuditLogsSecretsConfig) GetClientSecret() ModelsSecret {
	if o == nil {
		var ret ModelsSecret
		return ret
	}

	return o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value
// and a boolean to check if the value has been set.
func (o *WizAuditLogsSecretsConfig) GetClientSecretOk() (*ModelsSecret, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientSecret, true
}

// SetClientSecret sets field value
func (o *WizAuditLogsSecretsConfig) SetClientSecret(v ModelsSecret) {
	o.ClientSecret = v
}

func (o WizAuditLogsSecretsConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WizAuditLogsSecretsConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["client_id"] = o.ClientId
	toSerialize["client_secret"] = o.ClientSecret
	return toSerialize, nil
}

func (o *WizAuditLogsSecretsConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"client_id",
		"client_secret",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWizAuditLogsSecretsConfig := _WizAuditLogsSecretsConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWizAuditLogsSecretsConfig)

	if err != nil {
		return err
	}

	*o = WizAuditLogsSecretsConfig(varWizAuditLogsSecretsConfig)

	return err
}

type NullableWizAuditLogsSecretsConfig struct {
	value *WizAuditLogsSecretsConfig
	isSet bool
}

func (v NullableWizAuditLogsSecretsConfig) Get() *WizAuditLogsSecretsConfig {
	return v.value
}

func (v *NullableWizAuditLogsSecretsConfig) Set(val *WizAuditLogsSecretsConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableWizAuditLogsSecretsConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableWizAuditLogsSecretsConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWizAuditLogsSecretsConfig(val *WizAuditLogsSecretsConfig) *NullableWizAuditLogsSecretsConfig {
	return &NullableWizAuditLogsSecretsConfig{value: val, isSet: true}
}

func (v NullableWizAuditLogsSecretsConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWizAuditLogsSecretsConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


