/*
Monad Swagger API

This is the monad API

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package monad

import (
	"encoding/json"
)

// checks if the DriveActivitySettingsConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DriveActivitySettingsConfig{}

// DriveActivitySettingsConfig Google Workspace Drive Activity settings
type DriveActivitySettingsConfig struct {
	// Email address to use for authenticating with Google Cloud.
	Email *string `json:"email,omitempty"`
}

// NewDriveActivitySettingsConfig instantiates a new DriveActivitySettingsConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDriveActivitySettingsConfig() *DriveActivitySettingsConfig {
	this := DriveActivitySettingsConfig{}
	return &this
}

// NewDriveActivitySettingsConfigWithDefaults instantiates a new DriveActivitySettingsConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDriveActivitySettingsConfigWithDefaults() *DriveActivitySettingsConfig {
	this := DriveActivitySettingsConfig{}
	return &this
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *DriveActivitySettingsConfig) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DriveActivitySettingsConfig) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *DriveActivitySettingsConfig) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *DriveActivitySettingsConfig) SetEmail(v string) {
	o.Email = &v
}

func (o DriveActivitySettingsConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DriveActivitySettingsConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	return toSerialize, nil
}

type NullableDriveActivitySettingsConfig struct {
	value *DriveActivitySettingsConfig
	isSet bool
}

func (v NullableDriveActivitySettingsConfig) Get() *DriveActivitySettingsConfig {
	return v.value
}

func (v *NullableDriveActivitySettingsConfig) Set(val *DriveActivitySettingsConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableDriveActivitySettingsConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableDriveActivitySettingsConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDriveActivitySettingsConfig(val *DriveActivitySettingsConfig) *NullableDriveActivitySettingsConfig {
	return &NullableDriveActivitySettingsConfig{value: val, isSet: true}
}

func (v NullableDriveActivitySettingsConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDriveActivitySettingsConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


