/*
Monad API

Programmatically manage your security data pipelines, configure data sources and destinations, and automate your security operations.  ## Base URL  ``` {{BASE_URL}}/api ```  ## Authentication  The Monad API supports two authentication methods:  ### API Key  Include your API key in the `x-api-key` header:  ```bash curl -H \"x-api-key: YOUR_API_KEY\" \\   {{BASE_URL}}/api/v2/organizations/{org_id}/pipelines ```  ### JWT Bearer Token  Include your JWT token in the `Authorization` header:  ```bash curl -H \"Authorization: Bearer YOUR_JWT_TOKEN\" \\   {{BASE_URL}}/api/v2/organizations/{org_id}/pipelines ```  ## Quick Start  List your pipelines:  ```bash curl -H \"x-api-key: YOUR_API_KEY\" \\   {{BASE_URL}}/api/v2/organizations/{org_id}/pipelines ```  Create a new pipeline:  ```bash curl -X POST \\   -H \"x-api-key: YOUR_API_KEY\" \\   -H \"Content-Type: application/json\" \\   -d '{\"name\": \"My Pipeline\", \"description\": \"Pipeline description\"}' \\   {{BASE_URL}}/api/v2/organizations/{org_id}/pipelines ```  ## Rate Limits  API requests are subject to rate limiting. If you exceed the rate limit, you'll receive a `429 Too Many Requests` response. Implement exponential backoff in your applications to handle rate limiting gracefully.  ## Errors  The API uses standard HTTP status codes:  | Status Code | Description                                      | | ----------- | ------------------------------------------------ | | `200`       | Success                                          | | `201`       | Created                                          | | `400`       | Bad Request - Invalid parameters                 | | `401`       | Unauthorized - Invalid or missing authentication | | `403`       | Forbidden - Insufficient permissions             | | `404`       | Not Found - Resource doesn't exist               | | `429`       | Too Many Requests - Rate limit exceeded          | | `500`       | Internal Server Error                            | 

API version: 1.0
Contact: support@monad.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package monad

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SentryOrgAuditLogsSecretsConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SentryOrgAuditLogsSecretsConfig{}

// SentryOrgAuditLogsSecretsConfig Sentry Organization Audit Logs secrets
type SentryOrgAuditLogsSecretsConfig struct {
	AuthToken ModelsSecret `json:"auth_token"`
}

type _SentryOrgAuditLogsSecretsConfig SentryOrgAuditLogsSecretsConfig

// NewSentryOrgAuditLogsSecretsConfig instantiates a new SentryOrgAuditLogsSecretsConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSentryOrgAuditLogsSecretsConfig(authToken ModelsSecret) *SentryOrgAuditLogsSecretsConfig {
	this := SentryOrgAuditLogsSecretsConfig{}
	this.AuthToken = authToken
	return &this
}

// NewSentryOrgAuditLogsSecretsConfigWithDefaults instantiates a new SentryOrgAuditLogsSecretsConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSentryOrgAuditLogsSecretsConfigWithDefaults() *SentryOrgAuditLogsSecretsConfig {
	this := SentryOrgAuditLogsSecretsConfig{}
	return &this
}

// GetAuthToken returns the AuthToken field value
func (o *SentryOrgAuditLogsSecretsConfig) GetAuthToken() ModelsSecret {
	if o == nil {
		var ret ModelsSecret
		return ret
	}

	return o.AuthToken
}

// GetAuthTokenOk returns a tuple with the AuthToken field value
// and a boolean to check if the value has been set.
func (o *SentryOrgAuditLogsSecretsConfig) GetAuthTokenOk() (*ModelsSecret, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthToken, true
}

// SetAuthToken sets field value
func (o *SentryOrgAuditLogsSecretsConfig) SetAuthToken(v ModelsSecret) {
	o.AuthToken = v
}

func (o SentryOrgAuditLogsSecretsConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SentryOrgAuditLogsSecretsConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["auth_token"] = o.AuthToken
	return toSerialize, nil
}

func (o *SentryOrgAuditLogsSecretsConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"auth_token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSentryOrgAuditLogsSecretsConfig := _SentryOrgAuditLogsSecretsConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSentryOrgAuditLogsSecretsConfig)

	if err != nil {
		return err
	}

	*o = SentryOrgAuditLogsSecretsConfig(varSentryOrgAuditLogsSecretsConfig)

	return err
}

type NullableSentryOrgAuditLogsSecretsConfig struct {
	value *SentryOrgAuditLogsSecretsConfig
	isSet bool
}

func (v NullableSentryOrgAuditLogsSecretsConfig) Get() *SentryOrgAuditLogsSecretsConfig {
	return v.value
}

func (v *NullableSentryOrgAuditLogsSecretsConfig) Set(val *SentryOrgAuditLogsSecretsConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableSentryOrgAuditLogsSecretsConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableSentryOrgAuditLogsSecretsConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSentryOrgAuditLogsSecretsConfig(val *SentryOrgAuditLogsSecretsConfig) *NullableSentryOrgAuditLogsSecretsConfig {
	return &NullableSentryOrgAuditLogsSecretsConfig{value: val, isSet: true}
}

func (v NullableSentryOrgAuditLogsSecretsConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSentryOrgAuditLogsSecretsConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


