/*
Monad API

This is the monad API

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package monad

import (
	"encoding/json"
)

// checks if the OpalEventsSettingsConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpalEventsSettingsConfig{}

// OpalEventsSettingsConfig Opal Events settings
type OpalEventsSettingsConfig struct {
	// Date to start fetching data from. If not specified, a full sync is fetched on the first sync. All syncs thereafter will be incremental.
	BackfillStartTime *string `json:"backfill_start_time,omitempty"`
	// Generate synthetic demo data instead of connecting to the real data source.
	UseSyntheticData *bool `json:"use_synthetic_data,omitempty"`
}

// NewOpalEventsSettingsConfig instantiates a new OpalEventsSettingsConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpalEventsSettingsConfig() *OpalEventsSettingsConfig {
	this := OpalEventsSettingsConfig{}
	return &this
}

// NewOpalEventsSettingsConfigWithDefaults instantiates a new OpalEventsSettingsConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpalEventsSettingsConfigWithDefaults() *OpalEventsSettingsConfig {
	this := OpalEventsSettingsConfig{}
	return &this
}

// GetBackfillStartTime returns the BackfillStartTime field value if set, zero value otherwise.
func (o *OpalEventsSettingsConfig) GetBackfillStartTime() string {
	if o == nil || IsNil(o.BackfillStartTime) {
		var ret string
		return ret
	}
	return *o.BackfillStartTime
}

// GetBackfillStartTimeOk returns a tuple with the BackfillStartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpalEventsSettingsConfig) GetBackfillStartTimeOk() (*string, bool) {
	if o == nil || IsNil(o.BackfillStartTime) {
		return nil, false
	}
	return o.BackfillStartTime, true
}

// HasBackfillStartTime returns a boolean if a field has been set.
func (o *OpalEventsSettingsConfig) HasBackfillStartTime() bool {
	if o != nil && !IsNil(o.BackfillStartTime) {
		return true
	}

	return false
}

// SetBackfillStartTime gets a reference to the given string and assigns it to the BackfillStartTime field.
func (o *OpalEventsSettingsConfig) SetBackfillStartTime(v string) {
	o.BackfillStartTime = &v
}

// GetUseSyntheticData returns the UseSyntheticData field value if set, zero value otherwise.
func (o *OpalEventsSettingsConfig) GetUseSyntheticData() bool {
	if o == nil || IsNil(o.UseSyntheticData) {
		var ret bool
		return ret
	}
	return *o.UseSyntheticData
}

// GetUseSyntheticDataOk returns a tuple with the UseSyntheticData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpalEventsSettingsConfig) GetUseSyntheticDataOk() (*bool, bool) {
	if o == nil || IsNil(o.UseSyntheticData) {
		return nil, false
	}
	return o.UseSyntheticData, true
}

// HasUseSyntheticData returns a boolean if a field has been set.
func (o *OpalEventsSettingsConfig) HasUseSyntheticData() bool {
	if o != nil && !IsNil(o.UseSyntheticData) {
		return true
	}

	return false
}

// SetUseSyntheticData gets a reference to the given bool and assigns it to the UseSyntheticData field.
func (o *OpalEventsSettingsConfig) SetUseSyntheticData(v bool) {
	o.UseSyntheticData = &v
}

func (o OpalEventsSettingsConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpalEventsSettingsConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BackfillStartTime) {
		toSerialize["backfill_start_time"] = o.BackfillStartTime
	}
	if !IsNil(o.UseSyntheticData) {
		toSerialize["use_synthetic_data"] = o.UseSyntheticData
	}
	return toSerialize, nil
}

type NullableOpalEventsSettingsConfig struct {
	value *OpalEventsSettingsConfig
	isSet bool
}

func (v NullableOpalEventsSettingsConfig) Get() *OpalEventsSettingsConfig {
	return v.value
}

func (v *NullableOpalEventsSettingsConfig) Set(val *OpalEventsSettingsConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableOpalEventsSettingsConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableOpalEventsSettingsConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpalEventsSettingsConfig(val *OpalEventsSettingsConfig) *NullableOpalEventsSettingsConfig {
	return &NullableOpalEventsSettingsConfig{value: val, isSet: true}
}

func (v NullableOpalEventsSettingsConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpalEventsSettingsConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


