/*
Monad API

Programmatically manage your security data pipelines, configure data sources and destinations, and automate your security operations.  ## Base URL  ``` {{BASE_URL}}/api ```  ## Authentication  The Monad API supports two authentication methods:  ### API Key  Include your API key in the `x-api-key` header:  ```bash curl -H \"x-api-key: YOUR_API_KEY\" \\   {{BASE_URL}}/api/v2/organizations/{org_id}/pipelines ```  ### JWT Bearer Token  Include your JWT token in the `Authorization` header:  ```bash curl -H \"Authorization: Bearer YOUR_JWT_TOKEN\" \\   {{BASE_URL}}/api/v2/organizations/{org_id}/pipelines ```  ## Quick Start  List your pipelines:  ```bash curl -H \"x-api-key: YOUR_API_KEY\" \\   {{BASE_URL}}/api/v2/organizations/{org_id}/pipelines ```  Create a new pipeline:  ```bash curl -X POST \\   -H \"x-api-key: YOUR_API_KEY\" \\   -H \"Content-Type: application/json\" \\   -d '{\"name\": \"My Pipeline\", \"description\": \"Pipeline description\"}' \\   {{BASE_URL}}/api/v2/organizations/{org_id}/pipelines ```  ## Rate Limits  API requests are subject to rate limiting. If you exceed the rate limit, you'll receive a `429 Too Many Requests` response. Implement exponential backoff in your applications to handle rate limiting gracefully.  ## Errors  The API uses standard HTTP status codes:  | Status Code | Description                                      | | ----------- | ------------------------------------------------ | | `200`       | Success                                          | | `201`       | Created                                          | | `400`       | Bad Request - Invalid parameters                 | | `401`       | Unauthorized - Invalid or missing authentication | | `403`       | Forbidden - Insufficient permissions             | | `404`       | Not Found - Resource doesn't exist               | | `429`       | Too Many Requests - Rate limit exceeded          | | `500`       | Internal Server Error                            | 

API version: 1.0
Contact: support@monad.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package monad

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GreenhouseAuditLogsSettingsConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GreenhouseAuditLogsSettingsConfig{}

// GreenhouseAuditLogsSettingsConfig Greenhouse Audit Log settings
type GreenhouseAuditLogsSettingsConfig struct {
	// Date to start fetching data from. If not specified, a full sync is fetched on the first sync. All syncs thereafter will be incremental.
	BackfillStartTime *string `json:"backfill_start_time,omitempty"`
	// Generate synthetic demo data instead of connecting to the real data source.
	UseSyntheticData *bool `json:"use_synthetic_data,omitempty"`
	// ID of the user to harvest audit logs for
	UserId string `json:"user_id"`
}

type _GreenhouseAuditLogsSettingsConfig GreenhouseAuditLogsSettingsConfig

// NewGreenhouseAuditLogsSettingsConfig instantiates a new GreenhouseAuditLogsSettingsConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGreenhouseAuditLogsSettingsConfig(userId string) *GreenhouseAuditLogsSettingsConfig {
	this := GreenhouseAuditLogsSettingsConfig{}
	this.UserId = userId
	return &this
}

// NewGreenhouseAuditLogsSettingsConfigWithDefaults instantiates a new GreenhouseAuditLogsSettingsConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGreenhouseAuditLogsSettingsConfigWithDefaults() *GreenhouseAuditLogsSettingsConfig {
	this := GreenhouseAuditLogsSettingsConfig{}
	return &this
}

// GetBackfillStartTime returns the BackfillStartTime field value if set, zero value otherwise.
func (o *GreenhouseAuditLogsSettingsConfig) GetBackfillStartTime() string {
	if o == nil || IsNil(o.BackfillStartTime) {
		var ret string
		return ret
	}
	return *o.BackfillStartTime
}

// GetBackfillStartTimeOk returns a tuple with the BackfillStartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GreenhouseAuditLogsSettingsConfig) GetBackfillStartTimeOk() (*string, bool) {
	if o == nil || IsNil(o.BackfillStartTime) {
		return nil, false
	}
	return o.BackfillStartTime, true
}

// HasBackfillStartTime returns a boolean if a field has been set.
func (o *GreenhouseAuditLogsSettingsConfig) HasBackfillStartTime() bool {
	if o != nil && !IsNil(o.BackfillStartTime) {
		return true
	}

	return false
}

// SetBackfillStartTime gets a reference to the given string and assigns it to the BackfillStartTime field.
func (o *GreenhouseAuditLogsSettingsConfig) SetBackfillStartTime(v string) {
	o.BackfillStartTime = &v
}

// GetUseSyntheticData returns the UseSyntheticData field value if set, zero value otherwise.
func (o *GreenhouseAuditLogsSettingsConfig) GetUseSyntheticData() bool {
	if o == nil || IsNil(o.UseSyntheticData) {
		var ret bool
		return ret
	}
	return *o.UseSyntheticData
}

// GetUseSyntheticDataOk returns a tuple with the UseSyntheticData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GreenhouseAuditLogsSettingsConfig) GetUseSyntheticDataOk() (*bool, bool) {
	if o == nil || IsNil(o.UseSyntheticData) {
		return nil, false
	}
	return o.UseSyntheticData, true
}

// HasUseSyntheticData returns a boolean if a field has been set.
func (o *GreenhouseAuditLogsSettingsConfig) HasUseSyntheticData() bool {
	if o != nil && !IsNil(o.UseSyntheticData) {
		return true
	}

	return false
}

// SetUseSyntheticData gets a reference to the given bool and assigns it to the UseSyntheticData field.
func (o *GreenhouseAuditLogsSettingsConfig) SetUseSyntheticData(v bool) {
	o.UseSyntheticData = &v
}

// GetUserId returns the UserId field value
func (o *GreenhouseAuditLogsSettingsConfig) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *GreenhouseAuditLogsSettingsConfig) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *GreenhouseAuditLogsSettingsConfig) SetUserId(v string) {
	o.UserId = v
}

func (o GreenhouseAuditLogsSettingsConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GreenhouseAuditLogsSettingsConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BackfillStartTime) {
		toSerialize["backfill_start_time"] = o.BackfillStartTime
	}
	if !IsNil(o.UseSyntheticData) {
		toSerialize["use_synthetic_data"] = o.UseSyntheticData
	}
	toSerialize["user_id"] = o.UserId
	return toSerialize, nil
}

func (o *GreenhouseAuditLogsSettingsConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGreenhouseAuditLogsSettingsConfig := _GreenhouseAuditLogsSettingsConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGreenhouseAuditLogsSettingsConfig)

	if err != nil {
		return err
	}

	*o = GreenhouseAuditLogsSettingsConfig(varGreenhouseAuditLogsSettingsConfig)

	return err
}

type NullableGreenhouseAuditLogsSettingsConfig struct {
	value *GreenhouseAuditLogsSettingsConfig
	isSet bool
}

func (v NullableGreenhouseAuditLogsSettingsConfig) Get() *GreenhouseAuditLogsSettingsConfig {
	return v.value
}

func (v *NullableGreenhouseAuditLogsSettingsConfig) Set(val *GreenhouseAuditLogsSettingsConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableGreenhouseAuditLogsSettingsConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableGreenhouseAuditLogsSettingsConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGreenhouseAuditLogsSettingsConfig(val *GreenhouseAuditLogsSettingsConfig) *NullableGreenhouseAuditLogsSettingsConfig {
	return &NullableGreenhouseAuditLogsSettingsConfig{value: val, isSet: true}
}

func (v NullableGreenhouseAuditLogsSettingsConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGreenhouseAuditLogsSettingsConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


