/*
Monad API

This is the monad API

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package monad

import (
	"encoding/json"
)

// checks if the CloudflareRulesetsSettingsConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudflareRulesetsSettingsConfig{}

// CloudflareRulesetsSettingsConfig Cloudflare Rulesets settings
type CloudflareRulesetsSettingsConfig struct {
	// Your Cloudflare account ID (for account-level rulesets). Required if ZoneIDs is not specified.
	AccountId *string `json:"account_id,omitempty"`
	// Cron expression for scheduling the input
	Cron *string `json:"cron,omitempty"`
	// Generate synthetic demo data instead of connecting to the real data source.
	UseSyntheticData *bool `json:"use_synthetic_data,omitempty"`
	// List of zone IDs (for zone-level rulesets). If empty and AccountID is not specified, fetches from all zones.
	ZoneIds []string `json:"zone_ids,omitempty"`
}

// NewCloudflareRulesetsSettingsConfig instantiates a new CloudflareRulesetsSettingsConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudflareRulesetsSettingsConfig() *CloudflareRulesetsSettingsConfig {
	this := CloudflareRulesetsSettingsConfig{}
	return &this
}

// NewCloudflareRulesetsSettingsConfigWithDefaults instantiates a new CloudflareRulesetsSettingsConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudflareRulesetsSettingsConfigWithDefaults() *CloudflareRulesetsSettingsConfig {
	this := CloudflareRulesetsSettingsConfig{}
	return &this
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *CloudflareRulesetsSettingsConfig) GetAccountId() string {
	if o == nil || IsNil(o.AccountId) {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudflareRulesetsSettingsConfig) GetAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *CloudflareRulesetsSettingsConfig) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *CloudflareRulesetsSettingsConfig) SetAccountId(v string) {
	o.AccountId = &v
}

// GetCron returns the Cron field value if set, zero value otherwise.
func (o *CloudflareRulesetsSettingsConfig) GetCron() string {
	if o == nil || IsNil(o.Cron) {
		var ret string
		return ret
	}
	return *o.Cron
}

// GetCronOk returns a tuple with the Cron field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudflareRulesetsSettingsConfig) GetCronOk() (*string, bool) {
	if o == nil || IsNil(o.Cron) {
		return nil, false
	}
	return o.Cron, true
}

// HasCron returns a boolean if a field has been set.
func (o *CloudflareRulesetsSettingsConfig) HasCron() bool {
	if o != nil && !IsNil(o.Cron) {
		return true
	}

	return false
}

// SetCron gets a reference to the given string and assigns it to the Cron field.
func (o *CloudflareRulesetsSettingsConfig) SetCron(v string) {
	o.Cron = &v
}

// GetUseSyntheticData returns the UseSyntheticData field value if set, zero value otherwise.
func (o *CloudflareRulesetsSettingsConfig) GetUseSyntheticData() bool {
	if o == nil || IsNil(o.UseSyntheticData) {
		var ret bool
		return ret
	}
	return *o.UseSyntheticData
}

// GetUseSyntheticDataOk returns a tuple with the UseSyntheticData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudflareRulesetsSettingsConfig) GetUseSyntheticDataOk() (*bool, bool) {
	if o == nil || IsNil(o.UseSyntheticData) {
		return nil, false
	}
	return o.UseSyntheticData, true
}

// HasUseSyntheticData returns a boolean if a field has been set.
func (o *CloudflareRulesetsSettingsConfig) HasUseSyntheticData() bool {
	if o != nil && !IsNil(o.UseSyntheticData) {
		return true
	}

	return false
}

// SetUseSyntheticData gets a reference to the given bool and assigns it to the UseSyntheticData field.
func (o *CloudflareRulesetsSettingsConfig) SetUseSyntheticData(v bool) {
	o.UseSyntheticData = &v
}

// GetZoneIds returns the ZoneIds field value if set, zero value otherwise.
func (o *CloudflareRulesetsSettingsConfig) GetZoneIds() []string {
	if o == nil || IsNil(o.ZoneIds) {
		var ret []string
		return ret
	}
	return o.ZoneIds
}

// GetZoneIdsOk returns a tuple with the ZoneIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudflareRulesetsSettingsConfig) GetZoneIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.ZoneIds) {
		return nil, false
	}
	return o.ZoneIds, true
}

// HasZoneIds returns a boolean if a field has been set.
func (o *CloudflareRulesetsSettingsConfig) HasZoneIds() bool {
	if o != nil && !IsNil(o.ZoneIds) {
		return true
	}

	return false
}

// SetZoneIds gets a reference to the given []string and assigns it to the ZoneIds field.
func (o *CloudflareRulesetsSettingsConfig) SetZoneIds(v []string) {
	o.ZoneIds = v
}

func (o CloudflareRulesetsSettingsConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudflareRulesetsSettingsConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountId) {
		toSerialize["account_id"] = o.AccountId
	}
	if !IsNil(o.Cron) {
		toSerialize["cron"] = o.Cron
	}
	if !IsNil(o.UseSyntheticData) {
		toSerialize["use_synthetic_data"] = o.UseSyntheticData
	}
	if !IsNil(o.ZoneIds) {
		toSerialize["zone_ids"] = o.ZoneIds
	}
	return toSerialize, nil
}

type NullableCloudflareRulesetsSettingsConfig struct {
	value *CloudflareRulesetsSettingsConfig
	isSet bool
}

func (v NullableCloudflareRulesetsSettingsConfig) Get() *CloudflareRulesetsSettingsConfig {
	return v.value
}

func (v *NullableCloudflareRulesetsSettingsConfig) Set(val *CloudflareRulesetsSettingsConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudflareRulesetsSettingsConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudflareRulesetsSettingsConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudflareRulesetsSettingsConfig(val *CloudflareRulesetsSettingsConfig) *NullableCloudflareRulesetsSettingsConfig {
	return &NullableCloudflareRulesetsSettingsConfig{value: val, isSet: true}
}

func (v NullableCloudflareRulesetsSettingsConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudflareRulesetsSettingsConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


