/*
Monad API

Programmatically manage your security data pipelines, configure data sources and destinations, and automate your security operations.  ## Base URL  ``` {{BASE_URL}}/api ```  ## Authentication  The Monad API supports two authentication methods:  ### API Key  Include your API key in the `x-api-key` header:  ```bash curl -H \"x-api-key: YOUR_API_KEY\" \\   {{BASE_URL}}/api/v2/organizations/{org_id}/pipelines ```  ### JWT Bearer Token  Include your JWT token in the `Authorization` header:  ```bash curl -H \"Authorization: Bearer YOUR_JWT_TOKEN\" \\   {{BASE_URL}}/api/v2/organizations/{org_id}/pipelines ```  ## Quick Start  List your pipelines:  ```bash curl -H \"x-api-key: YOUR_API_KEY\" \\   {{BASE_URL}}/api/v2/organizations/{org_id}/pipelines ```  Create a new pipeline:  ```bash curl -X POST \\   -H \"x-api-key: YOUR_API_KEY\" \\   -H \"Content-Type: application/json\" \\   -d '{\"name\": \"My Pipeline\", \"description\": \"Pipeline description\"}' \\   {{BASE_URL}}/api/v2/organizations/{org_id}/pipelines ```  ## Rate Limits  API requests are subject to rate limiting. If you exceed the rate limit, you'll receive a `429 Too Many Requests` response. Implement exponential backoff in your applications to handle rate limiting gracefully.  ## Errors  The API uses standard HTTP status codes:  | Status Code | Description                                      | | ----------- | ------------------------------------------------ | | `200`       | Success                                          | | `201`       | Created                                          | | `400`       | Bad Request - Invalid parameters                 | | `401`       | Unauthorized - Invalid or missing authentication | | `403`       | Forbidden - Insufficient permissions             | | `404`       | Not Found - Resource doesn't exist               | | `429`       | Too Many Requests - Rate limit exceeded          | | `500`       | Internal Server Error                            | 

API version: 1.0
Contact: support@monad.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package monad

import (
	"encoding/json"
)

// checks if the TaniumGraphqlInputSecretsConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaniumGraphqlInputSecretsConfig{}

// TaniumGraphqlInputSecretsConfig struct for TaniumGraphqlInputSecretsConfig
type TaniumGraphqlInputSecretsConfig struct {
	ApiToken *ModelsSecret `json:"api_token,omitempty"`
}

// NewTaniumGraphqlInputSecretsConfig instantiates a new TaniumGraphqlInputSecretsConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaniumGraphqlInputSecretsConfig() *TaniumGraphqlInputSecretsConfig {
	this := TaniumGraphqlInputSecretsConfig{}
	return &this
}

// NewTaniumGraphqlInputSecretsConfigWithDefaults instantiates a new TaniumGraphqlInputSecretsConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaniumGraphqlInputSecretsConfigWithDefaults() *TaniumGraphqlInputSecretsConfig {
	this := TaniumGraphqlInputSecretsConfig{}
	return &this
}

// GetApiToken returns the ApiToken field value if set, zero value otherwise.
func (o *TaniumGraphqlInputSecretsConfig) GetApiToken() ModelsSecret {
	if o == nil || IsNil(o.ApiToken) {
		var ret ModelsSecret
		return ret
	}
	return *o.ApiToken
}

// GetApiTokenOk returns a tuple with the ApiToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaniumGraphqlInputSecretsConfig) GetApiTokenOk() (*ModelsSecret, bool) {
	if o == nil || IsNil(o.ApiToken) {
		return nil, false
	}
	return o.ApiToken, true
}

// HasApiToken returns a boolean if a field has been set.
func (o *TaniumGraphqlInputSecretsConfig) HasApiToken() bool {
	if o != nil && !IsNil(o.ApiToken) {
		return true
	}

	return false
}

// SetApiToken gets a reference to the given ModelsSecret and assigns it to the ApiToken field.
func (o *TaniumGraphqlInputSecretsConfig) SetApiToken(v ModelsSecret) {
	o.ApiToken = &v
}

func (o TaniumGraphqlInputSecretsConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaniumGraphqlInputSecretsConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApiToken) {
		toSerialize["api_token"] = o.ApiToken
	}
	return toSerialize, nil
}

type NullableTaniumGraphqlInputSecretsConfig struct {
	value *TaniumGraphqlInputSecretsConfig
	isSet bool
}

func (v NullableTaniumGraphqlInputSecretsConfig) Get() *TaniumGraphqlInputSecretsConfig {
	return v.value
}

func (v *NullableTaniumGraphqlInputSecretsConfig) Set(val *TaniumGraphqlInputSecretsConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableTaniumGraphqlInputSecretsConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableTaniumGraphqlInputSecretsConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaniumGraphqlInputSecretsConfig(val *TaniumGraphqlInputSecretsConfig) *NullableTaniumGraphqlInputSecretsConfig {
	return &NullableTaniumGraphqlInputSecretsConfig{value: val, isSet: true}
}

func (v NullableTaniumGraphqlInputSecretsConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaniumGraphqlInputSecretsConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


