/*
Monad API

Programmatically manage your security data pipelines, configure data sources and destinations, and automate your security operations.  ## Base URL  ``` {{BASE_URL}}/api ```  ## Authentication  The Monad API supports two authentication methods:  ### API Key  Include your API key in the `x-api-key` header:  ```bash curl -H \"x-api-key: YOUR_API_KEY\" \\   {{BASE_URL}}/api/v2/organizations/{org_id}/pipelines ```  ### JWT Bearer Token  Include your JWT token in the `Authorization` header:  ```bash curl -H \"Authorization: Bearer YOUR_JWT_TOKEN\" \\   {{BASE_URL}}/api/v2/organizations/{org_id}/pipelines ```  ## Quick Start  List your pipelines:  ```bash curl -H \"x-api-key: YOUR_API_KEY\" \\   {{BASE_URL}}/api/v2/organizations/{org_id}/pipelines ```  Create a new pipeline:  ```bash curl -X POST \\   -H \"x-api-key: YOUR_API_KEY\" \\   -H \"Content-Type: application/json\" \\   -d '{\"name\": \"My Pipeline\", \"description\": \"Pipeline description\"}' \\   {{BASE_URL}}/api/v2/organizations/{org_id}/pipelines ```  ## Rate Limits  API requests are subject to rate limiting. If you exceed the rate limit, you'll receive a `429 Too Many Requests` response. Implement exponential backoff in your applications to handle rate limiting gracefully.  ## Errors  The API uses standard HTTP status codes:  | Status Code | Description                                      | | ----------- | ------------------------------------------------ | | `200`       | Success                                          | | `201`       | Created                                          | | `400`       | Bad Request - Invalid parameters                 | | `401`       | Unauthorized - Invalid or missing authentication | | `403`       | Forbidden - Insufficient permissions             | | `404`       | Not Found - Resource doesn't exist               | | `429`       | Too Many Requests - Rate limit exceeded          | | `500`       | Internal Server Error                            | 

API version: 1.0
Contact: support@monad.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package monad

import (
	"encoding/json"
)

// checks if the SplunkSecretsConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SplunkSecretsConfig{}

// SplunkSecretsConfig Splunk Output Secrets
type SplunkSecretsConfig struct {
	Password *ModelsSecret `json:"password,omitempty"`
	Token *ModelsSecret `json:"token,omitempty"`
}

// NewSplunkSecretsConfig instantiates a new SplunkSecretsConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSplunkSecretsConfig() *SplunkSecretsConfig {
	this := SplunkSecretsConfig{}
	return &this
}

// NewSplunkSecretsConfigWithDefaults instantiates a new SplunkSecretsConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSplunkSecretsConfigWithDefaults() *SplunkSecretsConfig {
	this := SplunkSecretsConfig{}
	return &this
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *SplunkSecretsConfig) GetPassword() ModelsSecret {
	if o == nil || IsNil(o.Password) {
		var ret ModelsSecret
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SplunkSecretsConfig) GetPasswordOk() (*ModelsSecret, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *SplunkSecretsConfig) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given ModelsSecret and assigns it to the Password field.
func (o *SplunkSecretsConfig) SetPassword(v ModelsSecret) {
	o.Password = &v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *SplunkSecretsConfig) GetToken() ModelsSecret {
	if o == nil || IsNil(o.Token) {
		var ret ModelsSecret
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SplunkSecretsConfig) GetTokenOk() (*ModelsSecret, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *SplunkSecretsConfig) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given ModelsSecret and assigns it to the Token field.
func (o *SplunkSecretsConfig) SetToken(v ModelsSecret) {
	o.Token = &v
}

func (o SplunkSecretsConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SplunkSecretsConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	return toSerialize, nil
}

type NullableSplunkSecretsConfig struct {
	value *SplunkSecretsConfig
	isSet bool
}

func (v NullableSplunkSecretsConfig) Get() *SplunkSecretsConfig {
	return v.value
}

func (v *NullableSplunkSecretsConfig) Set(val *SplunkSecretsConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableSplunkSecretsConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableSplunkSecretsConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSplunkSecretsConfig(val *SplunkSecretsConfig) *NullableSplunkSecretsConfig {
	return &NullableSplunkSecretsConfig{value: val, isSet: true}
}

func (v NullableSplunkSecretsConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSplunkSecretsConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


