/*
Monad API

This is the monad API

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package monad

import (
	"encoding/json"
)

// checks if the WizAuditLogsSettingsConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WizAuditLogsSettingsConfig{}

// WizAuditLogsSettingsConfig Wiz Audit Logs settings
type WizAuditLogsSettingsConfig struct {
	// Date to start fetching data from up to 180 days. If not specified, a sync of 180 days back is fetched on the first sync. All syncs thereafter will be incremental.
	BackfillStartTime *string `json:"backfill_start_time,omitempty"`
	// DataCenter represents the tenant's data center location. Enter a tenant data center, e.g., \"us1\", \"us2\", \"us3\"
	TenantDataCenter *string `json:"tenant_data_center,omitempty"`
	// Generate synthetic demo data instead of connecting to the real data source.
	UseSyntheticData *bool `json:"use_synthetic_data,omitempty"`
}

// NewWizAuditLogsSettingsConfig instantiates a new WizAuditLogsSettingsConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWizAuditLogsSettingsConfig() *WizAuditLogsSettingsConfig {
	this := WizAuditLogsSettingsConfig{}
	return &this
}

// NewWizAuditLogsSettingsConfigWithDefaults instantiates a new WizAuditLogsSettingsConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWizAuditLogsSettingsConfigWithDefaults() *WizAuditLogsSettingsConfig {
	this := WizAuditLogsSettingsConfig{}
	return &this
}

// GetBackfillStartTime returns the BackfillStartTime field value if set, zero value otherwise.
func (o *WizAuditLogsSettingsConfig) GetBackfillStartTime() string {
	if o == nil || IsNil(o.BackfillStartTime) {
		var ret string
		return ret
	}
	return *o.BackfillStartTime
}

// GetBackfillStartTimeOk returns a tuple with the BackfillStartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WizAuditLogsSettingsConfig) GetBackfillStartTimeOk() (*string, bool) {
	if o == nil || IsNil(o.BackfillStartTime) {
		return nil, false
	}
	return o.BackfillStartTime, true
}

// HasBackfillStartTime returns a boolean if a field has been set.
func (o *WizAuditLogsSettingsConfig) HasBackfillStartTime() bool {
	if o != nil && !IsNil(o.BackfillStartTime) {
		return true
	}

	return false
}

// SetBackfillStartTime gets a reference to the given string and assigns it to the BackfillStartTime field.
func (o *WizAuditLogsSettingsConfig) SetBackfillStartTime(v string) {
	o.BackfillStartTime = &v
}

// GetTenantDataCenter returns the TenantDataCenter field value if set, zero value otherwise.
func (o *WizAuditLogsSettingsConfig) GetTenantDataCenter() string {
	if o == nil || IsNil(o.TenantDataCenter) {
		var ret string
		return ret
	}
	return *o.TenantDataCenter
}

// GetTenantDataCenterOk returns a tuple with the TenantDataCenter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WizAuditLogsSettingsConfig) GetTenantDataCenterOk() (*string, bool) {
	if o == nil || IsNil(o.TenantDataCenter) {
		return nil, false
	}
	return o.TenantDataCenter, true
}

// HasTenantDataCenter returns a boolean if a field has been set.
func (o *WizAuditLogsSettingsConfig) HasTenantDataCenter() bool {
	if o != nil && !IsNil(o.TenantDataCenter) {
		return true
	}

	return false
}

// SetTenantDataCenter gets a reference to the given string and assigns it to the TenantDataCenter field.
func (o *WizAuditLogsSettingsConfig) SetTenantDataCenter(v string) {
	o.TenantDataCenter = &v
}

// GetUseSyntheticData returns the UseSyntheticData field value if set, zero value otherwise.
func (o *WizAuditLogsSettingsConfig) GetUseSyntheticData() bool {
	if o == nil || IsNil(o.UseSyntheticData) {
		var ret bool
		return ret
	}
	return *o.UseSyntheticData
}

// GetUseSyntheticDataOk returns a tuple with the UseSyntheticData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WizAuditLogsSettingsConfig) GetUseSyntheticDataOk() (*bool, bool) {
	if o == nil || IsNil(o.UseSyntheticData) {
		return nil, false
	}
	return o.UseSyntheticData, true
}

// HasUseSyntheticData returns a boolean if a field has been set.
func (o *WizAuditLogsSettingsConfig) HasUseSyntheticData() bool {
	if o != nil && !IsNil(o.UseSyntheticData) {
		return true
	}

	return false
}

// SetUseSyntheticData gets a reference to the given bool and assigns it to the UseSyntheticData field.
func (o *WizAuditLogsSettingsConfig) SetUseSyntheticData(v bool) {
	o.UseSyntheticData = &v
}

func (o WizAuditLogsSettingsConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WizAuditLogsSettingsConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BackfillStartTime) {
		toSerialize["backfill_start_time"] = o.BackfillStartTime
	}
	if !IsNil(o.TenantDataCenter) {
		toSerialize["tenant_data_center"] = o.TenantDataCenter
	}
	if !IsNil(o.UseSyntheticData) {
		toSerialize["use_synthetic_data"] = o.UseSyntheticData
	}
	return toSerialize, nil
}

type NullableWizAuditLogsSettingsConfig struct {
	value *WizAuditLogsSettingsConfig
	isSet bool
}

func (v NullableWizAuditLogsSettingsConfig) Get() *WizAuditLogsSettingsConfig {
	return v.value
}

func (v *NullableWizAuditLogsSettingsConfig) Set(val *WizAuditLogsSettingsConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableWizAuditLogsSettingsConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableWizAuditLogsSettingsConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWizAuditLogsSettingsConfig(val *WizAuditLogsSettingsConfig) *NullableWizAuditLogsSettingsConfig {
	return &NullableWizAuditLogsSettingsConfig{value: val, isSet: true}
}

func (v NullableWizAuditLogsSettingsConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWizAuditLogsSettingsConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


