/*
Monad API

This is the monad API

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package monad

import (
	"encoding/json"
)

// checks if the CommunityTransformsInternalTransformConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommunityTransformsInternalTransformConfig{}

// CommunityTransformsInternalTransformConfig struct for CommunityTransformsInternalTransformConfig
type CommunityTransformsInternalTransformConfig struct {
	Author *string `json:"author,omitempty"`
	Config map[string]interface{} `json:"config,omitempty"`
	Contributors []string `json:"contributors,omitempty"`
	Description *string `json:"description,omitempty"`
	Inputs []string `json:"inputs,omitempty"`
	Name *string `json:"name,omitempty"`
	Tags []string `json:"tags,omitempty"`
}

// NewCommunityTransformsInternalTransformConfig instantiates a new CommunityTransformsInternalTransformConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommunityTransformsInternalTransformConfig() *CommunityTransformsInternalTransformConfig {
	this := CommunityTransformsInternalTransformConfig{}
	return &this
}

// NewCommunityTransformsInternalTransformConfigWithDefaults instantiates a new CommunityTransformsInternalTransformConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommunityTransformsInternalTransformConfigWithDefaults() *CommunityTransformsInternalTransformConfig {
	this := CommunityTransformsInternalTransformConfig{}
	return &this
}

// GetAuthor returns the Author field value if set, zero value otherwise.
func (o *CommunityTransformsInternalTransformConfig) GetAuthor() string {
	if o == nil || IsNil(o.Author) {
		var ret string
		return ret
	}
	return *o.Author
}

// GetAuthorOk returns a tuple with the Author field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityTransformsInternalTransformConfig) GetAuthorOk() (*string, bool) {
	if o == nil || IsNil(o.Author) {
		return nil, false
	}
	return o.Author, true
}

// HasAuthor returns a boolean if a field has been set.
func (o *CommunityTransformsInternalTransformConfig) HasAuthor() bool {
	if o != nil && !IsNil(o.Author) {
		return true
	}

	return false
}

// SetAuthor gets a reference to the given string and assigns it to the Author field.
func (o *CommunityTransformsInternalTransformConfig) SetAuthor(v string) {
	o.Author = &v
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *CommunityTransformsInternalTransformConfig) GetConfig() map[string]interface{} {
	if o == nil || IsNil(o.Config) {
		var ret map[string]interface{}
		return ret
	}
	return o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityTransformsInternalTransformConfig) GetConfigOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Config) {
		return map[string]interface{}{}, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *CommunityTransformsInternalTransformConfig) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given map[string]interface{} and assigns it to the Config field.
func (o *CommunityTransformsInternalTransformConfig) SetConfig(v map[string]interface{}) {
	o.Config = v
}

// GetContributors returns the Contributors field value if set, zero value otherwise.
func (o *CommunityTransformsInternalTransformConfig) GetContributors() []string {
	if o == nil || IsNil(o.Contributors) {
		var ret []string
		return ret
	}
	return o.Contributors
}

// GetContributorsOk returns a tuple with the Contributors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityTransformsInternalTransformConfig) GetContributorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Contributors) {
		return nil, false
	}
	return o.Contributors, true
}

// HasContributors returns a boolean if a field has been set.
func (o *CommunityTransformsInternalTransformConfig) HasContributors() bool {
	if o != nil && !IsNil(o.Contributors) {
		return true
	}

	return false
}

// SetContributors gets a reference to the given []string and assigns it to the Contributors field.
func (o *CommunityTransformsInternalTransformConfig) SetContributors(v []string) {
	o.Contributors = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CommunityTransformsInternalTransformConfig) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityTransformsInternalTransformConfig) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CommunityTransformsInternalTransformConfig) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CommunityTransformsInternalTransformConfig) SetDescription(v string) {
	o.Description = &v
}

// GetInputs returns the Inputs field value if set, zero value otherwise.
func (o *CommunityTransformsInternalTransformConfig) GetInputs() []string {
	if o == nil || IsNil(o.Inputs) {
		var ret []string
		return ret
	}
	return o.Inputs
}

// GetInputsOk returns a tuple with the Inputs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityTransformsInternalTransformConfig) GetInputsOk() ([]string, bool) {
	if o == nil || IsNil(o.Inputs) {
		return nil, false
	}
	return o.Inputs, true
}

// HasInputs returns a boolean if a field has been set.
func (o *CommunityTransformsInternalTransformConfig) HasInputs() bool {
	if o != nil && !IsNil(o.Inputs) {
		return true
	}

	return false
}

// SetInputs gets a reference to the given []string and assigns it to the Inputs field.
func (o *CommunityTransformsInternalTransformConfig) SetInputs(v []string) {
	o.Inputs = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CommunityTransformsInternalTransformConfig) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityTransformsInternalTransformConfig) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CommunityTransformsInternalTransformConfig) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CommunityTransformsInternalTransformConfig) SetName(v string) {
	o.Name = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *CommunityTransformsInternalTransformConfig) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityTransformsInternalTransformConfig) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *CommunityTransformsInternalTransformConfig) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *CommunityTransformsInternalTransformConfig) SetTags(v []string) {
	o.Tags = v
}

func (o CommunityTransformsInternalTransformConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommunityTransformsInternalTransformConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Author) {
		toSerialize["author"] = o.Author
	}
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	if !IsNil(o.Contributors) {
		toSerialize["contributors"] = o.Contributors
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Inputs) {
		toSerialize["inputs"] = o.Inputs
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	return toSerialize, nil
}

type NullableCommunityTransformsInternalTransformConfig struct {
	value *CommunityTransformsInternalTransformConfig
	isSet bool
}

func (v NullableCommunityTransformsInternalTransformConfig) Get() *CommunityTransformsInternalTransformConfig {
	return v.value
}

func (v *NullableCommunityTransformsInternalTransformConfig) Set(val *CommunityTransformsInternalTransformConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableCommunityTransformsInternalTransformConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableCommunityTransformsInternalTransformConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommunityTransformsInternalTransformConfig(val *CommunityTransformsInternalTransformConfig) *NullableCommunityTransformsInternalTransformConfig {
	return &NullableCommunityTransformsInternalTransformConfig{value: val, isSet: true}
}

func (v NullableCommunityTransformsInternalTransformConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommunityTransformsInternalTransformConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


