/*
Monad Swagger API

This is the monad API

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package monad

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RoutesUpdateTransformRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoutesUpdateTransformRequest{}

// RoutesUpdateTransformRequest struct for RoutesUpdateTransformRequest
type RoutesUpdateTransformRequest struct {
	Config map[string]interface{} `json:"config,omitempty"`
	Description *string `json:"description,omitempty"`
	Name string `json:"name"`
}

type _RoutesUpdateTransformRequest RoutesUpdateTransformRequest

// NewRoutesUpdateTransformRequest instantiates a new RoutesUpdateTransformRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoutesUpdateTransformRequest(name string) *RoutesUpdateTransformRequest {
	this := RoutesUpdateTransformRequest{}
	this.Name = name
	return &this
}

// NewRoutesUpdateTransformRequestWithDefaults instantiates a new RoutesUpdateTransformRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoutesUpdateTransformRequestWithDefaults() *RoutesUpdateTransformRequest {
	this := RoutesUpdateTransformRequest{}
	return &this
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *RoutesUpdateTransformRequest) GetConfig() map[string]interface{} {
	if o == nil || IsNil(o.Config) {
		var ret map[string]interface{}
		return ret
	}
	return o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesUpdateTransformRequest) GetConfigOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Config) {
		return map[string]interface{}{}, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *RoutesUpdateTransformRequest) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given map[string]interface{} and assigns it to the Config field.
func (o *RoutesUpdateTransformRequest) SetConfig(v map[string]interface{}) {
	o.Config = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *RoutesUpdateTransformRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesUpdateTransformRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *RoutesUpdateTransformRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *RoutesUpdateTransformRequest) SetDescription(v string) {
	o.Description = &v
}

// GetName returns the Name field value
func (o *RoutesUpdateTransformRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RoutesUpdateTransformRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RoutesUpdateTransformRequest) SetName(v string) {
	o.Name = v
}

func (o RoutesUpdateTransformRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoutesUpdateTransformRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *RoutesUpdateTransformRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRoutesUpdateTransformRequest := _RoutesUpdateTransformRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRoutesUpdateTransformRequest)

	if err != nil {
		return err
	}

	*o = RoutesUpdateTransformRequest(varRoutesUpdateTransformRequest)

	return err
}

type NullableRoutesUpdateTransformRequest struct {
	value *RoutesUpdateTransformRequest
	isSet bool
}

func (v NullableRoutesUpdateTransformRequest) Get() *RoutesUpdateTransformRequest {
	return v.value
}

func (v *NullableRoutesUpdateTransformRequest) Set(val *RoutesUpdateTransformRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRoutesUpdateTransformRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRoutesUpdateTransformRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoutesUpdateTransformRequest(val *RoutesUpdateTransformRequest) *NullableRoutesUpdateTransformRequest {
	return &NullableRoutesUpdateTransformRequest{value: val, isSet: true}
}

func (v NullableRoutesUpdateTransformRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoutesUpdateTransformRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


