/*
 * Monad API
 * This is the monad API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@monad.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.ModelsOutput;
import org.openapitools.client.model.ModelsOutputList;
import org.openapitools.client.model.ResponderErrorResponse;
import org.openapitools.client.model.RoutesGetOutputResponse;
import org.openapitools.client.model.RoutesV2CreateOutputRequest;
import org.openapitools.client.model.RoutesV2PutOutputRequest;
import org.openapitools.client.model.RoutesV2SuccessResponse;
import org.openapitools.client.model.RoutesV2TestOutputConnectionRequest;
import org.openapitools.client.model.RoutesV2UpdateOutputRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class OrganizationOutputsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public OrganizationOutputsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public OrganizationOutputsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createOutput
     * @param organizationId Organization ID (required)
     * @param routesV2CreateOutputRequest Output configuration (required)
     * @param testConnection Test connection before creating the input (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Output created successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request body, output type, configuration validation error, or secret processing error </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createOutputCall(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull RoutesV2CreateOutputRequest routesV2CreateOutputRequest, @javax.annotation.Nullable Boolean testConnection, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = routesV2CreateOutputRequest;

        // create path and map variables
        String localVarPath = "/v2/{organization_id}/outputs"
            .replace("{" + "organization_id" + "}", localVarApiClient.escapeString(organizationId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (testConnection != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("test_connection", testConnection));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "Bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createOutputValidateBeforeCall(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull RoutesV2CreateOutputRequest routesV2CreateOutputRequest, @javax.annotation.Nullable Boolean testConnection, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'organizationId' is set
        if (organizationId == null) {
            throw new ApiException("Missing the required parameter 'organizationId' when calling createOutput(Async)");
        }

        // verify the required parameter 'routesV2CreateOutputRequest' is set
        if (routesV2CreateOutputRequest == null) {
            throw new ApiException("Missing the required parameter 'routesV2CreateOutputRequest' when calling createOutput(Async)");
        }

        return createOutputCall(organizationId, routesV2CreateOutputRequest, testConnection, _callback);

    }

    /**
     * Create output
     * Create a new output with configuration including secrets handling
     * @param organizationId Organization ID (required)
     * @param routesV2CreateOutputRequest Output configuration (required)
     * @param testConnection Test connection before creating the input (optional)
     * @return ModelsOutput
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Output created successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request body, output type, configuration validation error, or secret processing error </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public ModelsOutput createOutput(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull RoutesV2CreateOutputRequest routesV2CreateOutputRequest, @javax.annotation.Nullable Boolean testConnection) throws ApiException {
        ApiResponse<ModelsOutput> localVarResp = createOutputWithHttpInfo(organizationId, routesV2CreateOutputRequest, testConnection);
        return localVarResp.getData();
    }

    /**
     * Create output
     * Create a new output with configuration including secrets handling
     * @param organizationId Organization ID (required)
     * @param routesV2CreateOutputRequest Output configuration (required)
     * @param testConnection Test connection before creating the input (optional)
     * @return ApiResponse&lt;ModelsOutput&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Output created successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request body, output type, configuration validation error, or secret processing error </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ModelsOutput> createOutputWithHttpInfo(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull RoutesV2CreateOutputRequest routesV2CreateOutputRequest, @javax.annotation.Nullable Boolean testConnection) throws ApiException {
        okhttp3.Call localVarCall = createOutputValidateBeforeCall(organizationId, routesV2CreateOutputRequest, testConnection, null);
        Type localVarReturnType = new TypeToken<ModelsOutput>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create output (asynchronously)
     * Create a new output with configuration including secrets handling
     * @param organizationId Organization ID (required)
     * @param routesV2CreateOutputRequest Output configuration (required)
     * @param testConnection Test connection before creating the input (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Output created successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request body, output type, configuration validation error, or secret processing error </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createOutputAsync(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull RoutesV2CreateOutputRequest routesV2CreateOutputRequest, @javax.annotation.Nullable Boolean testConnection, final ApiCallback<ModelsOutput> _callback) throws ApiException {

        okhttp3.Call localVarCall = createOutputValidateBeforeCall(organizationId, routesV2CreateOutputRequest, testConnection, _callback);
        Type localVarReturnType = new TypeToken<ModelsOutput>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteOrganizationOutput
     * @param organizationId Organization ID (required)
     * @param outputId Output ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Output deleted successfully </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Failed to delete output </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteOrganizationOutputCall(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull String outputId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/{organization_id}/outputs/{output_id}"
            .replace("{" + "organization_id" + "}", localVarApiClient.escapeString(organizationId.toString()))
            .replace("{" + "output_id" + "}", localVarApiClient.escapeString(outputId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "Bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteOrganizationOutputValidateBeforeCall(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull String outputId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'organizationId' is set
        if (organizationId == null) {
            throw new ApiException("Missing the required parameter 'organizationId' when calling deleteOrganizationOutput(Async)");
        }

        // verify the required parameter 'outputId' is set
        if (outputId == null) {
            throw new ApiException("Missing the required parameter 'outputId' when calling deleteOrganizationOutput(Async)");
        }

        return deleteOrganizationOutputCall(organizationId, outputId, _callback);

    }

    /**
     * Delete output
     * Delete output
     * @param organizationId Organization ID (required)
     * @param outputId Output ID (required)
     * @return String
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Output deleted successfully </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Failed to delete output </td><td>  -  </td></tr>
     </table>
     */
    public String deleteOrganizationOutput(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull String outputId) throws ApiException {
        ApiResponse<String> localVarResp = deleteOrganizationOutputWithHttpInfo(organizationId, outputId);
        return localVarResp.getData();
    }

    /**
     * Delete output
     * Delete output
     * @param organizationId Organization ID (required)
     * @param outputId Output ID (required)
     * @return ApiResponse&lt;String&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Output deleted successfully </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Failed to delete output </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<String> deleteOrganizationOutputWithHttpInfo(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull String outputId) throws ApiException {
        okhttp3.Call localVarCall = deleteOrganizationOutputValidateBeforeCall(organizationId, outputId, null);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Delete output (asynchronously)
     * Delete output
     * @param organizationId Organization ID (required)
     * @param outputId Output ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Output deleted successfully </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Failed to delete output </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteOrganizationOutputAsync(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull String outputId, final ApiCallback<String> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteOrganizationOutputValidateBeforeCall(organizationId, outputId, _callback);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getOrganizationOutput
     * @param organizationId Organization ID (required)
     * @param outputId Output ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Output retrieved successfully </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Failed to get output </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getOrganizationOutputCall(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull String outputId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/{organization_id}/outputs/{output_id}"
            .replace("{" + "organization_id" + "}", localVarApiClient.escapeString(organizationId.toString()))
            .replace("{" + "output_id" + "}", localVarApiClient.escapeString(outputId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "Bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getOrganizationOutputValidateBeforeCall(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull String outputId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'organizationId' is set
        if (organizationId == null) {
            throw new ApiException("Missing the required parameter 'organizationId' when calling getOrganizationOutput(Async)");
        }

        // verify the required parameter 'outputId' is set
        if (outputId == null) {
            throw new ApiException("Missing the required parameter 'outputId' when calling getOrganizationOutput(Async)");
        }

        return getOrganizationOutputCall(organizationId, outputId, _callback);

    }

    /**
     * Get a output
     * Get a configured output in organization
     * @param organizationId Organization ID (required)
     * @param outputId Output ID (required)
     * @return RoutesGetOutputResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Output retrieved successfully </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Failed to get output </td><td>  -  </td></tr>
     </table>
     */
    public RoutesGetOutputResponse getOrganizationOutput(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull String outputId) throws ApiException {
        ApiResponse<RoutesGetOutputResponse> localVarResp = getOrganizationOutputWithHttpInfo(organizationId, outputId);
        return localVarResp.getData();
    }

    /**
     * Get a output
     * Get a configured output in organization
     * @param organizationId Organization ID (required)
     * @param outputId Output ID (required)
     * @return ApiResponse&lt;RoutesGetOutputResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Output retrieved successfully </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Failed to get output </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<RoutesGetOutputResponse> getOrganizationOutputWithHttpInfo(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull String outputId) throws ApiException {
        okhttp3.Call localVarCall = getOrganizationOutputValidateBeforeCall(organizationId, outputId, null);
        Type localVarReturnType = new TypeToken<RoutesGetOutputResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get a output (asynchronously)
     * Get a configured output in organization
     * @param organizationId Organization ID (required)
     * @param outputId Output ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Output retrieved successfully </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Failed to get output </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getOrganizationOutputAsync(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull String outputId, final ApiCallback<RoutesGetOutputResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getOrganizationOutputValidateBeforeCall(organizationId, outputId, _callback);
        Type localVarReturnType = new TypeToken<RoutesGetOutputResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listOrganizationOutputs
     * @param organizationId Organization ID (required)
     * @param limit Limit (optional)
     * @param offset Offset (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of outputs </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Failed to marshal outputs </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listOrganizationOutputsCall(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/{organization_id}/outputs"
            .replace("{" + "organization_id" + "}", localVarApiClient.escapeString(organizationId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (offset != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("offset", offset));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "Bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listOrganizationOutputsValidateBeforeCall(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'organizationId' is set
        if (organizationId == null) {
            throw new ApiException("Missing the required parameter 'organizationId' when calling listOrganizationOutputs(Async)");
        }

        return listOrganizationOutputsCall(organizationId, limit, offset, _callback);

    }

    /**
     * List configured outputs in organization
     * List outputs
     * @param organizationId Organization ID (required)
     * @param limit Limit (optional)
     * @param offset Offset (optional)
     * @return ModelsOutputList
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of outputs </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Failed to marshal outputs </td><td>  -  </td></tr>
     </table>
     */
    public ModelsOutputList listOrganizationOutputs(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset) throws ApiException {
        ApiResponse<ModelsOutputList> localVarResp = listOrganizationOutputsWithHttpInfo(organizationId, limit, offset);
        return localVarResp.getData();
    }

    /**
     * List configured outputs in organization
     * List outputs
     * @param organizationId Organization ID (required)
     * @param limit Limit (optional)
     * @param offset Offset (optional)
     * @return ApiResponse&lt;ModelsOutputList&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of outputs </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Failed to marshal outputs </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ModelsOutputList> listOrganizationOutputsWithHttpInfo(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset) throws ApiException {
        okhttp3.Call localVarCall = listOrganizationOutputsValidateBeforeCall(organizationId, limit, offset, null);
        Type localVarReturnType = new TypeToken<ModelsOutputList>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List configured outputs in organization (asynchronously)
     * List outputs
     * @param organizationId Organization ID (required)
     * @param limit Limit (optional)
     * @param offset Offset (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of outputs </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Failed to marshal outputs </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listOrganizationOutputsAsync(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, final ApiCallback<ModelsOutputList> _callback) throws ApiException {

        okhttp3.Call localVarCall = listOrganizationOutputsValidateBeforeCall(organizationId, limit, offset, _callback);
        Type localVarReturnType = new TypeToken<ModelsOutputList>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for replaceOutput
     * @param organizationId Organization ID (required)
     * @param outputId Output ID (required)
     * @param routesV2PutOutputRequest Output configuration update (required)
     * @param testConnection Test connection before creating the input (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Output updated successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request body, output type, configuration validation error, or secret processing error </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Output not found </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call replaceOutputCall(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull String outputId, @javax.annotation.Nonnull RoutesV2PutOutputRequest routesV2PutOutputRequest, @javax.annotation.Nullable Boolean testConnection, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = routesV2PutOutputRequest;

        // create path and map variables
        String localVarPath = "/v2/{organization_id}/outputs/{output_id}"
            .replace("{" + "organization_id" + "}", localVarApiClient.escapeString(organizationId.toString()))
            .replace("{" + "output_id" + "}", localVarApiClient.escapeString(outputId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (testConnection != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("test_connection", testConnection));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "Bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call replaceOutputValidateBeforeCall(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull String outputId, @javax.annotation.Nonnull RoutesV2PutOutputRequest routesV2PutOutputRequest, @javax.annotation.Nullable Boolean testConnection, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'organizationId' is set
        if (organizationId == null) {
            throw new ApiException("Missing the required parameter 'organizationId' when calling replaceOutput(Async)");
        }

        // verify the required parameter 'outputId' is set
        if (outputId == null) {
            throw new ApiException("Missing the required parameter 'outputId' when calling replaceOutput(Async)");
        }

        // verify the required parameter 'routesV2PutOutputRequest' is set
        if (routesV2PutOutputRequest == null) {
            throw new ApiException("Missing the required parameter 'routesV2PutOutputRequest' when calling replaceOutput(Async)");
        }

        return replaceOutputCall(organizationId, outputId, routesV2PutOutputRequest, testConnection, _callback);

    }

    /**
     * Replace output
     * Replace an existing output with new configuration including secrets handling
     * @param organizationId Organization ID (required)
     * @param outputId Output ID (required)
     * @param routesV2PutOutputRequest Output configuration update (required)
     * @param testConnection Test connection before creating the input (optional)
     * @return ModelsOutput
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Output updated successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request body, output type, configuration validation error, or secret processing error </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Output not found </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public ModelsOutput replaceOutput(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull String outputId, @javax.annotation.Nonnull RoutesV2PutOutputRequest routesV2PutOutputRequest, @javax.annotation.Nullable Boolean testConnection) throws ApiException {
        ApiResponse<ModelsOutput> localVarResp = replaceOutputWithHttpInfo(organizationId, outputId, routesV2PutOutputRequest, testConnection);
        return localVarResp.getData();
    }

    /**
     * Replace output
     * Replace an existing output with new configuration including secrets handling
     * @param organizationId Organization ID (required)
     * @param outputId Output ID (required)
     * @param routesV2PutOutputRequest Output configuration update (required)
     * @param testConnection Test connection before creating the input (optional)
     * @return ApiResponse&lt;ModelsOutput&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Output updated successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request body, output type, configuration validation error, or secret processing error </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Output not found </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ModelsOutput> replaceOutputWithHttpInfo(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull String outputId, @javax.annotation.Nonnull RoutesV2PutOutputRequest routesV2PutOutputRequest, @javax.annotation.Nullable Boolean testConnection) throws ApiException {
        okhttp3.Call localVarCall = replaceOutputValidateBeforeCall(organizationId, outputId, routesV2PutOutputRequest, testConnection, null);
        Type localVarReturnType = new TypeToken<ModelsOutput>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Replace output (asynchronously)
     * Replace an existing output with new configuration including secrets handling
     * @param organizationId Organization ID (required)
     * @param outputId Output ID (required)
     * @param routesV2PutOutputRequest Output configuration update (required)
     * @param testConnection Test connection before creating the input (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Output updated successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request body, output type, configuration validation error, or secret processing error </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Output not found </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call replaceOutputAsync(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull String outputId, @javax.annotation.Nonnull RoutesV2PutOutputRequest routesV2PutOutputRequest, @javax.annotation.Nullable Boolean testConnection, final ApiCallback<ModelsOutput> _callback) throws ApiException {

        okhttp3.Call localVarCall = replaceOutputValidateBeforeCall(organizationId, outputId, routesV2PutOutputRequest, testConnection, _callback);
        Type localVarReturnType = new TypeToken<ModelsOutput>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for testOutputConnection
     * @param organizationId Organization ID (required)
     * @param routesV2TestOutputConnectionRequest Output configuration to test (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Connection test successful </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request body, output type, or configuration </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call testOutputConnectionCall(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull RoutesV2TestOutputConnectionRequest routesV2TestOutputConnectionRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = routesV2TestOutputConnectionRequest;

        // create path and map variables
        String localVarPath = "/v2/{organization_id}/outputs/test-connection"
            .replace("{" + "organization_id" + "}", localVarApiClient.escapeString(organizationId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "Bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call testOutputConnectionValidateBeforeCall(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull RoutesV2TestOutputConnectionRequest routesV2TestOutputConnectionRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'organizationId' is set
        if (organizationId == null) {
            throw new ApiException("Missing the required parameter 'organizationId' when calling testOutputConnection(Async)");
        }

        // verify the required parameter 'routesV2TestOutputConnectionRequest' is set
        if (routesV2TestOutputConnectionRequest == null) {
            throw new ApiException("Missing the required parameter 'routesV2TestOutputConnectionRequest' when calling testOutputConnection(Async)");
        }

        return testOutputConnectionCall(organizationId, routesV2TestOutputConnectionRequest, _callback);

    }

    /**
     * Test output connection
     * Tests the connection for a given output type and configuration
     * @param organizationId Organization ID (required)
     * @param routesV2TestOutputConnectionRequest Output configuration to test (required)
     * @return RoutesV2SuccessResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Connection test successful </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request body, output type, or configuration </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public RoutesV2SuccessResponse testOutputConnection(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull RoutesV2TestOutputConnectionRequest routesV2TestOutputConnectionRequest) throws ApiException {
        ApiResponse<RoutesV2SuccessResponse> localVarResp = testOutputConnectionWithHttpInfo(organizationId, routesV2TestOutputConnectionRequest);
        return localVarResp.getData();
    }

    /**
     * Test output connection
     * Tests the connection for a given output type and configuration
     * @param organizationId Organization ID (required)
     * @param routesV2TestOutputConnectionRequest Output configuration to test (required)
     * @return ApiResponse&lt;RoutesV2SuccessResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Connection test successful </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request body, output type, or configuration </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<RoutesV2SuccessResponse> testOutputConnectionWithHttpInfo(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull RoutesV2TestOutputConnectionRequest routesV2TestOutputConnectionRequest) throws ApiException {
        okhttp3.Call localVarCall = testOutputConnectionValidateBeforeCall(organizationId, routesV2TestOutputConnectionRequest, null);
        Type localVarReturnType = new TypeToken<RoutesV2SuccessResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Test output connection (asynchronously)
     * Tests the connection for a given output type and configuration
     * @param organizationId Organization ID (required)
     * @param routesV2TestOutputConnectionRequest Output configuration to test (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Connection test successful </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request body, output type, or configuration </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call testOutputConnectionAsync(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull RoutesV2TestOutputConnectionRequest routesV2TestOutputConnectionRequest, final ApiCallback<RoutesV2SuccessResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = testOutputConnectionValidateBeforeCall(organizationId, routesV2TestOutputConnectionRequest, _callback);
        Type localVarReturnType = new TypeToken<RoutesV2SuccessResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateOutput
     * @param organizationId Organization ID (required)
     * @param outputId Output ID (required)
     * @param routesV2UpdateOutputRequest Output configuration update (required)
     * @param testConnection Test connection before creating the input (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Output updated successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request body, output type, configuration validation error, or secret processing error </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Output not found </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateOutputCall(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull String outputId, @javax.annotation.Nonnull RoutesV2UpdateOutputRequest routesV2UpdateOutputRequest, @javax.annotation.Nullable Boolean testConnection, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = routesV2UpdateOutputRequest;

        // create path and map variables
        String localVarPath = "/v2/{organization_id}/outputs/{output_id}"
            .replace("{" + "organization_id" + "}", localVarApiClient.escapeString(organizationId.toString()))
            .replace("{" + "output_id" + "}", localVarApiClient.escapeString(outputId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (testConnection != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("test_connection", testConnection));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "Bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateOutputValidateBeforeCall(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull String outputId, @javax.annotation.Nonnull RoutesV2UpdateOutputRequest routesV2UpdateOutputRequest, @javax.annotation.Nullable Boolean testConnection, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'organizationId' is set
        if (organizationId == null) {
            throw new ApiException("Missing the required parameter 'organizationId' when calling updateOutput(Async)");
        }

        // verify the required parameter 'outputId' is set
        if (outputId == null) {
            throw new ApiException("Missing the required parameter 'outputId' when calling updateOutput(Async)");
        }

        // verify the required parameter 'routesV2UpdateOutputRequest' is set
        if (routesV2UpdateOutputRequest == null) {
            throw new ApiException("Missing the required parameter 'routesV2UpdateOutputRequest' when calling updateOutput(Async)");
        }

        return updateOutputCall(organizationId, outputId, routesV2UpdateOutputRequest, testConnection, _callback);

    }

    /**
     * Update output
     * Update an existing output with new configuration including secrets handling
     * @param organizationId Organization ID (required)
     * @param outputId Output ID (required)
     * @param routesV2UpdateOutputRequest Output configuration update (required)
     * @param testConnection Test connection before creating the input (optional)
     * @return ModelsOutput
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Output updated successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request body, output type, configuration validation error, or secret processing error </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Output not found </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public ModelsOutput updateOutput(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull String outputId, @javax.annotation.Nonnull RoutesV2UpdateOutputRequest routesV2UpdateOutputRequest, @javax.annotation.Nullable Boolean testConnection) throws ApiException {
        ApiResponse<ModelsOutput> localVarResp = updateOutputWithHttpInfo(organizationId, outputId, routesV2UpdateOutputRequest, testConnection);
        return localVarResp.getData();
    }

    /**
     * Update output
     * Update an existing output with new configuration including secrets handling
     * @param organizationId Organization ID (required)
     * @param outputId Output ID (required)
     * @param routesV2UpdateOutputRequest Output configuration update (required)
     * @param testConnection Test connection before creating the input (optional)
     * @return ApiResponse&lt;ModelsOutput&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Output updated successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request body, output type, configuration validation error, or secret processing error </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Output not found </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ModelsOutput> updateOutputWithHttpInfo(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull String outputId, @javax.annotation.Nonnull RoutesV2UpdateOutputRequest routesV2UpdateOutputRequest, @javax.annotation.Nullable Boolean testConnection) throws ApiException {
        okhttp3.Call localVarCall = updateOutputValidateBeforeCall(organizationId, outputId, routesV2UpdateOutputRequest, testConnection, null);
        Type localVarReturnType = new TypeToken<ModelsOutput>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update output (asynchronously)
     * Update an existing output with new configuration including secrets handling
     * @param organizationId Organization ID (required)
     * @param outputId Output ID (required)
     * @param routesV2UpdateOutputRequest Output configuration update (required)
     * @param testConnection Test connection before creating the input (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Output updated successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request body, output type, configuration validation error, or secret processing error </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Output not found </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateOutputAsync(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull String outputId, @javax.annotation.Nonnull RoutesV2UpdateOutputRequest routesV2UpdateOutputRequest, @javax.annotation.Nullable Boolean testConnection, final ApiCallback<ModelsOutput> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateOutputValidateBeforeCall(organizationId, outputId, routesV2UpdateOutputRequest, testConnection, _callback);
        Type localVarReturnType = new TypeToken<ModelsOutput>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
