/*
 * Monad API
 * Programmatically manage your security data pipelines, configure data sources and destinations, and automate your security operations.  ## Base URL  ``` {{BASE_URL}}/api ```  ## Authentication  The Monad API supports two authentication methods:  ### API Key  Include your API key in the `x-api-key` header:  ```bash curl -H \"x-api-key: YOUR_API_KEY\" \\   {{BASE_URL}}/api/v2/organizations/{org_id}/pipelines ```  ### JWT Bearer Token  Include your JWT token in the `Authorization` header:  ```bash curl -H \"Authorization: Bearer YOUR_JWT_TOKEN\" \\   {{BASE_URL}}/api/v2/organizations/{org_id}/pipelines ```  ## Quick Start  List your pipelines:  ```bash curl -H \"x-api-key: YOUR_API_KEY\" \\   {{BASE_URL}}/api/v2/organizations/{org_id}/pipelines ```  Create a new pipeline:  ```bash curl -X POST \\   -H \"x-api-key: YOUR_API_KEY\" \\   -H \"Content-Type: application/json\" \\   -d '{\"name\": \"My Pipeline\", \"description\": \"Pipeline description\"}' \\   {{BASE_URL}}/api/v2/organizations/{org_id}/pipelines ```  ## Rate Limits  API requests are subject to rate limiting. If you exceed the rate limit, you'll receive a `429 Too Many Requests` response. Implement exponential backoff in your applications to handle rate limiting gracefully.  ## Errors  The API uses standard HTTP status codes:  | Status Code | Description                                      | | ----------- | ------------------------------------------------ | | `200`       | Success                                          | | `201`       | Created                                          | | `400`       | Bad Request - Invalid parameters                 | | `401`       | Unauthorized - Invalid or missing authentication | | `403`       | Forbidden - Insufficient permissions             | | `404`       | Not Found - Resource doesn't exist               | | `429`       | Too Many Requests - Rate limit exceeded          | | `500`       | Internal Server Error                            | 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@monad.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.ApplyTransformationV2Request;
import org.openapitools.client.model.GenerateRecordRequest;
import org.openapitools.client.model.ResponderErrorResponse;
import org.openapitools.client.model.RoutesV2ApplyTransformationResponse;
import org.openapitools.client.model.RoutesV2GenerateRecordResponse;
import org.openapitools.client.model.RoutesV2ListTemplatesResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TransformSandboxApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public TransformSandboxApi() {
        this(Configuration.getDefaultApiClient());
    }

    public TransformSandboxApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for applyTransformation
     * @param organizationId Organization ID (required)
     * @param applyTransformationV2Request Transform configuration and record (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call applyTransformationCall(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull ApplyTransformationV2Request applyTransformationV2Request, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = applyTransformationV2Request;

        // create path and map variables
        String localVarPath = "/v2/{organization_id}/sandbox/transform"
            .replace("{" + "organization_id" + "}", localVarApiClient.escapeString(organizationId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "Bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call applyTransformationValidateBeforeCall(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull ApplyTransformationV2Request applyTransformationV2Request, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'organizationId' is set
        if (organizationId == null) {
            throw new ApiException("Missing the required parameter 'organizationId' when calling applyTransformation(Async)");
        }

        // verify the required parameter 'applyTransformationV2Request' is set
        if (applyTransformationV2Request == null) {
            throw new ApiException("Missing the required parameter 'applyTransformationV2Request' when calling applyTransformation(Async)");
        }

        return applyTransformationCall(organizationId, applyTransformationV2Request, _callback);

    }

    /**
     * Apply transformation to record
     * Apply a transformation configuration to a JSON record, resolving secret references from the organization
     * @param organizationId Organization ID (required)
     * @param applyTransformationV2Request Transform configuration and record (required)
     * @return RoutesV2ApplyTransformationResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public RoutesV2ApplyTransformationResponse applyTransformation(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull ApplyTransformationV2Request applyTransformationV2Request) throws ApiException {
        ApiResponse<RoutesV2ApplyTransformationResponse> localVarResp = applyTransformationWithHttpInfo(organizationId, applyTransformationV2Request);
        return localVarResp.getData();
    }

    /**
     * Apply transformation to record
     * Apply a transformation configuration to a JSON record, resolving secret references from the organization
     * @param organizationId Organization ID (required)
     * @param applyTransformationV2Request Transform configuration and record (required)
     * @return ApiResponse&lt;RoutesV2ApplyTransformationResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<RoutesV2ApplyTransformationResponse> applyTransformationWithHttpInfo(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull ApplyTransformationV2Request applyTransformationV2Request) throws ApiException {
        okhttp3.Call localVarCall = applyTransformationValidateBeforeCall(organizationId, applyTransformationV2Request, null);
        Type localVarReturnType = new TypeToken<RoutesV2ApplyTransformationResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Apply transformation to record (asynchronously)
     * Apply a transformation configuration to a JSON record, resolving secret references from the organization
     * @param organizationId Organization ID (required)
     * @param applyTransformationV2Request Transform configuration and record (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call applyTransformationAsync(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nonnull ApplyTransformationV2Request applyTransformationV2Request, final ApiCallback<RoutesV2ApplyTransformationResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = applyTransformationValidateBeforeCall(organizationId, applyTransformationV2Request, _callback);
        Type localVarReturnType = new TypeToken<RoutesV2ApplyTransformationResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for applyTransformationV2
     * @param applyTransformationV2Request Transform configuration and record (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call applyTransformationV2Call(@javax.annotation.Nonnull ApplyTransformationV2Request applyTransformationV2Request, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = applyTransformationV2Request;

        // create path and map variables
        String localVarPath = "/v2/sandbox/transform";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "Bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call applyTransformationV2ValidateBeforeCall(@javax.annotation.Nonnull ApplyTransformationV2Request applyTransformationV2Request, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'applyTransformationV2Request' is set
        if (applyTransformationV2Request == null) {
            throw new ApiException("Missing the required parameter 'applyTransformationV2Request' when calling applyTransformationV2(Async)");
        }

        return applyTransformationV2Call(applyTransformationV2Request, _callback);

    }

    /**
     * Apply transformation to record
     * Apply a transformation configuration to a JSON record
     * @param applyTransformationV2Request Transform configuration and record (required)
     * @return RoutesV2ApplyTransformationResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public RoutesV2ApplyTransformationResponse applyTransformationV2(@javax.annotation.Nonnull ApplyTransformationV2Request applyTransformationV2Request) throws ApiException {
        ApiResponse<RoutesV2ApplyTransformationResponse> localVarResp = applyTransformationV2WithHttpInfo(applyTransformationV2Request);
        return localVarResp.getData();
    }

    /**
     * Apply transformation to record
     * Apply a transformation configuration to a JSON record
     * @param applyTransformationV2Request Transform configuration and record (required)
     * @return ApiResponse&lt;RoutesV2ApplyTransformationResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<RoutesV2ApplyTransformationResponse> applyTransformationV2WithHttpInfo(@javax.annotation.Nonnull ApplyTransformationV2Request applyTransformationV2Request) throws ApiException {
        okhttp3.Call localVarCall = applyTransformationV2ValidateBeforeCall(applyTransformationV2Request, null);
        Type localVarReturnType = new TypeToken<RoutesV2ApplyTransformationResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Apply transformation to record (asynchronously)
     * Apply a transformation configuration to a JSON record
     * @param applyTransformationV2Request Transform configuration and record (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call applyTransformationV2Async(@javax.annotation.Nonnull ApplyTransformationV2Request applyTransformationV2Request, final ApiCallback<RoutesV2ApplyTransformationResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = applyTransformationV2ValidateBeforeCall(applyTransformationV2Request, _callback);
        Type localVarReturnType = new TypeToken<RoutesV2ApplyTransformationResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for generateRecord
     * @param generateRecordRequest Record generation parameters (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call generateRecordCall(@javax.annotation.Nonnull GenerateRecordRequest generateRecordRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = generateRecordRequest;

        // create path and map variables
        String localVarPath = "/v2/sandbox/template";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "Bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call generateRecordValidateBeforeCall(@javax.annotation.Nonnull GenerateRecordRequest generateRecordRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'generateRecordRequest' is set
        if (generateRecordRequest == null) {
            throw new ApiException("Missing the required parameter 'generateRecordRequest' when calling generateRecord(Async)");
        }

        return generateRecordCall(generateRecordRequest, _callback);

    }

    /**
     * Generate sample record
     * Generate a sample record using the specified template type
     * @param generateRecordRequest Record generation parameters (required)
     * @return RoutesV2GenerateRecordResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public RoutesV2GenerateRecordResponse generateRecord(@javax.annotation.Nonnull GenerateRecordRequest generateRecordRequest) throws ApiException {
        ApiResponse<RoutesV2GenerateRecordResponse> localVarResp = generateRecordWithHttpInfo(generateRecordRequest);
        return localVarResp.getData();
    }

    /**
     * Generate sample record
     * Generate a sample record using the specified template type
     * @param generateRecordRequest Record generation parameters (required)
     * @return ApiResponse&lt;RoutesV2GenerateRecordResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<RoutesV2GenerateRecordResponse> generateRecordWithHttpInfo(@javax.annotation.Nonnull GenerateRecordRequest generateRecordRequest) throws ApiException {
        okhttp3.Call localVarCall = generateRecordValidateBeforeCall(generateRecordRequest, null);
        Type localVarReturnType = new TypeToken<RoutesV2GenerateRecordResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Generate sample record (asynchronously)
     * Generate a sample record using the specified template type
     * @param generateRecordRequest Record generation parameters (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call generateRecordAsync(@javax.annotation.Nonnull GenerateRecordRequest generateRecordRequest, final ApiCallback<RoutesV2GenerateRecordResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = generateRecordValidateBeforeCall(generateRecordRequest, _callback);
        Type localVarReturnType = new TypeToken<RoutesV2GenerateRecordResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listTemplates
     * @param body  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of template names </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listTemplatesCall(@javax.annotation.Nullable Object body, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = body;

        // create path and map variables
        String localVarPath = "/v2/sandbox/template";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "Bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listTemplatesValidateBeforeCall(@javax.annotation.Nullable Object body, final ApiCallback _callback) throws ApiException {
        return listTemplatesCall(body, _callback);

    }

    /**
     * List available templates
     * Get a list of all valid record type templates
     * @param body  (optional)
     * @return RoutesV2ListTemplatesResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of template names </td><td>  -  </td></tr>
     </table>
     */
    public RoutesV2ListTemplatesResponse listTemplates(@javax.annotation.Nullable Object body) throws ApiException {
        ApiResponse<RoutesV2ListTemplatesResponse> localVarResp = listTemplatesWithHttpInfo(body);
        return localVarResp.getData();
    }

    /**
     * List available templates
     * Get a list of all valid record type templates
     * @param body  (optional)
     * @return ApiResponse&lt;RoutesV2ListTemplatesResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of template names </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<RoutesV2ListTemplatesResponse> listTemplatesWithHttpInfo(@javax.annotation.Nullable Object body) throws ApiException {
        okhttp3.Call localVarCall = listTemplatesValidateBeforeCall(body, null);
        Type localVarReturnType = new TypeToken<RoutesV2ListTemplatesResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List available templates (asynchronously)
     * Get a list of all valid record type templates
     * @param body  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of template names </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listTemplatesAsync(@javax.annotation.Nullable Object body, final ApiCallback<RoutesV2ListTemplatesResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = listTemplatesValidateBeforeCall(body, _callback);
        Type localVarReturnType = new TypeToken<RoutesV2ListTemplatesResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
