/*
 * Monad API
 * This is the monad API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@monad.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.BatchConfigBatchConfig;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DatabricksSettingsConfig
 */
public class DatabricksSettingsConfigTest {
    private final DatabricksSettingsConfig model = new DatabricksSettingsConfig();

    /**
     * Model tests for DatabricksSettingsConfig
     */
    @Test
    public void testDatabricksSettingsConfig() {
        // TODO: test DatabricksSettingsConfig
    }

    /**
     * Test the property 'batchConfig'
     */
    @Test
    public void batchConfigTest() {
        // TODO: test batchConfig
    }

    /**
     * Test the property 'catalog'
     */
    @Test
    public void catalogTest() {
        // TODO: test catalog
    }

    /**
     * Test the property 'httpPath'
     */
    @Test
    public void httpPathTest() {
        // TODO: test httpPath
    }

    /**
     * Test the property 'schema'
     */
    @Test
    public void schemaTest() {
        // TODO: test schema
    }

    /**
     * Test the property 'serverHostname'
     */
    @Test
    public void serverHostnameTest() {
        // TODO: test serverHostname
    }

    /**
     * Test the property 'table'
     */
    @Test
    public void tableTest() {
        // TODO: test table
    }

    /**
     * Test the property 'volume'
     */
    @Test
    public void volumeTest() {
        // TODO: test volume
    }

}
