/*
 * Monad Swagger API
 * This is the monad API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UsersSecretsConfig
 */
public class UsersSecretsConfigTest {
    private final UsersSecretsConfig model = new UsersSecretsConfig();

    /**
     * Model tests for UsersSecretsConfig
     */
    @Test
    public void testUsersSecretsConfig() {
        // TODO: test UsersSecretsConfig
    }

    /**
     * Test the property 'credentialsJson'
     */
    @Test
    public void credentialsJsonTest() {
        // TODO: test credentialsJson
    }

    /**
     * Test the property 'customerId'
     */
    @Test
    public void customerIdTest() {
        // TODO: test customerId
    }

    /**
     * Test the property 'domain'
     */
    @Test
    public void domainTest() {
        // TODO: test domain
    }

}
