# coding: utf-8

"""
    Monad API

    This is the monad API

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from monad.models.models_data_usage import ModelsDataUsage
from monad.models.models_pipeline_node_status import ModelsPipelineNodeStatus
from typing import Optional, Set
from typing_extensions import Self

class ModelsPipelineStatus(BaseModel):
    """
    ModelsPipelineStatus
    """ # noqa: E501
    egress: Optional[ModelsDataUsage] = None
    errors: Optional[StrictInt] = None
    expired_messages: Optional[StrictInt] = None
    ingress: Optional[ModelsDataUsage] = None
    nodes: Optional[List[ModelsPipelineNodeStatus]] = None
    organization_id: Optional[StrictStr] = None
    organization_name: Optional[StrictStr] = None
    pipeline_id: Optional[StrictStr] = None
    pipeline_name: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["egress", "errors", "expired_messages", "ingress", "nodes", "organization_id", "organization_name", "pipeline_id", "pipeline_name", "status"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModelsPipelineStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of egress
        if self.egress:
            _dict['egress'] = self.egress.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ingress
        if self.ingress:
            _dict['ingress'] = self.ingress.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in nodes (list)
        _items = []
        if self.nodes:
            for _item_nodes in self.nodes:
                if _item_nodes:
                    _items.append(_item_nodes.to_dict())
            _dict['nodes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModelsPipelineStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "egress": ModelsDataUsage.from_dict(obj["egress"]) if obj.get("egress") is not None else None,
            "errors": obj.get("errors"),
            "expired_messages": obj.get("expired_messages"),
            "ingress": ModelsDataUsage.from_dict(obj["ingress"]) if obj.get("ingress") is not None else None,
            "nodes": [ModelsPipelineNodeStatus.from_dict(_item) for _item in obj["nodes"]] if obj.get("nodes") is not None else None,
            "organization_id": obj.get("organization_id"),
            "organization_name": obj.get("organization_name"),
            "pipeline_id": obj.get("pipeline_id"),
            "pipeline_name": obj.get("pipeline_name"),
            "status": obj.get("status")
        })
        return _obj


